(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const KEY = 'the-last-save-browser-v1';
  const SLOT = `${KEY}:slot:`;
  const CHARACTERS = {twilight:['СУМЕРЕЧНАЯ ИСКРА','МАГИЯ'],fluttershy:['ФЛАТТЕРШАЙ','ЭМПАТИЯ'],pinkie:['ПИНКИ ПАЙ','ХАОС'],applejack:['ЭППЛДЖЕК','УРОЖАЙ'],rarity:['РЭЙНБОУ?','ФОКУС'],rainbow:['РАДУГА ДЭШ','СКОРОСТЬ']};
  const NPCS = ['Сумеречная Искорка','Флаттершай','Пинки Пай','Эпплджек','Рэрити','Радуга Дэш'];
  const initial = () => ({player:null,act:0,scene:'prologue',location:'Понивилль',chapter:'ПРОЛОГ — ОБЫЧНЫЙ ДЕНЬ',friendship:15,courage:15,attention:15,trust:15,memory:0,corruption:0,saves:0,loads:0,loops:0,inventory:[],endings:[],games:{},visits:{},difficulty:'НОРМАЛЬНО',newGamePlus:false,relationships:Object.fromEntries(NPCS.map(n=>[n,20]))});
  let S = readState();
  let cleanup = null;
  function readState(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&typeof x==='object'?x:initial()}catch{return initial()}}
  function persist(){localStorage.setItem(KEY,JSON.stringify(S))}
  function clamp(x){return Math.max(0,Math.min(100,Math.round(Number(x)||0)))}
  function add(k,n){S[k]=clamp((S[k]||0)+n)}
  function rel(n,nr){S.relationships[n]=clamp((S.relationships[n]||0)+nr)}
  function item(n){if(!S.inventory.includes(n))S.inventory.push(n)}
  function gameDone(n,msg){S.games[n]=(S.games[n]||0)+1;add('friendship',2);add('memory',1);persist();const m=$('overlay').querySelector('.modal');m.insertAdjacentHTML('beforeend',`<p>${msg}</p><button class="mini-btn" id="continueMini">ПРОДОЛЖИТЬ</button>`);$('continueMini').onclick=closeModal}
  function showGame(){ $('menu').classList.add('hidden'); $('game').classList.remove('hidden') }
  function showMenu(){ $('game').classList.add('hidden'); $('menu').classList.remove('hidden'); menu() }
  function menu(){const label=S.corruption>65?'ТЫ УЖЕ ИГРАЛА В ЭТО.':S.corruption>30?'НАЧАТЬ ЗАНОВО':'НОВАЯ ИГРА';$('menu').innerHTML=`<div class="menu-card"><h1 class="title">MY LITTLE PONY:<br>THE LAST SAVE</h1><div class="subtitle">Дружбу ещё никто не удалял.</div><div class="menu-buttons"><button class="menu-btn" id="newGame">${label}<span class="small">начать ещё один обычный день</span></button><button class="menu-btn" id="loadGame">ЗАГРУЗИТЬ ИГРУ<span class="small">сохранения помнят больше, чем ты</span></button><button class="menu-btn" id="gallery">ГАЛЕРЕЯ<span class="small">${S.endings.length}/6 концовок</span></button><button class="menu-btn" id="settings">НАСТРОЙКИ<span class="small">сложность · доступность</span></button><button class="menu-btn" id="about">ОБ ИГРЕ<span class="small">хоррор о памяти</span></button></div><div class="footer">браузерная версия · локальные сохранения · 18 мини-игр</div></div>`;$('newGame').onclick=chooseCharacter;$('loadGame').onclick=loadMenu;$('gallery').onclick=gallery;$('settings').onclick=settings;$('about').onclick=()=>modal('ОБ ИГРЕ','<p><b>THE LAST SAVE</b> — браузерное хоррор-приключение о памяти, повторениях и мире, который отказывается меняться.</p>')}
  function modal(title,html){$('overlay').classList.remove('hidden');$('overlay').innerHTML=`<div class="modal"><button class="close" id="modalClose">✕</button><h2>${title}</h2>${html}</div>`;$('modalClose').onclick=closeModal}
  function closeModal(){if(cleanup){cleanup();cleanup=null}$('overlay').classList.add('hidden');$('overlay').innerHTML=''}
  function chooseCharacter(){const html=Object.entries(CHARACTERS).map(([id,c])=>`<button class="slot" data-char="${id}"><b>${c[0]}</b><br><span class="note">ОСОБЕННОСТЬ: ${c[1]}</span></button>`).join('');modal('ВЫБЕРИ ПЕРСОНАЖА',`<p>Выбери того, кто войдёт в первый цикл.</p><div class="modal-grid">${html}</div>`);document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{const old=S;S=initial();S.player=b.dataset.char;S.loops=old.loops||0;S.endings=Array.isArray(old.endings)?old.endings:[];S.difficulty=old.difficulty||'НОРМАЛЬНО';S.newGamePlus=!!old.newGamePlus;S.memory=S.newGamePlus?clamp(old.memory+15):0;S.corruption=S.newGamePlus?Math.max(0,clamp(old.corruption)-10):0;if(S.newGamePlus)add('attention',20);persist();closeModal();showGame();prologue()})}
  function renderScene(text,choices,location=S.location,chapter=S.chapter){S.location=location;S.chapter=chapter;S.visits[location]=(S.visits[location]||0)+1;persist();$('chapterLabel').textContent=chapter;$('clockLabel').textContent=S.corruption>=40?'23:07':'09:14';$('locationTitle').textContent=location;$('scene').innerHTML=text.replace(/\n/g,'<br>');$('choices').innerHTML=choices.map((c,i)=>`<button class="choice-btn" data-choice="${i}"><strong>${i+1}.</strong> ${c[0]}</button>`).join('');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choices[Number(b.dataset.choice)][1]());document.body.classList.toggle('corrupted',S.corruption>=55);hud()}
  function hud(){const c=CHARACTERS[S.player];$('portrait').textContent=c?c[0][0]:'?';$('playerName').textContent=c?`${c[0]} · ${c[1]}`:'ПЕРСОНАЖ НЕ ВЫБРАН';const stats=[['ДРУЖБА',S.friendship],['СМЕЛОСТЬ',S.courage],['ВНИМАТЕЛЬНОСТЬ',S.attention],['ДОВЕРИЕ',S.trust],['ПАМЯТЬ',S.memory]];$('stats').innerHTML=stats.map(([n,v])=>`<div class="stat"><b><span>${n}</span><span>${clamp(v)}</span></b><div class="bar"><i style="width:${clamp(v)}%"></i></div></div>`).join('');$('relationships').innerHTML=NPCS.map(n=>`<div class="rel"><b><span>${n}</span><span>${clamp(S.relationships[n])}%</span></b><div class="bar"><i style="width:${clamp(S.relationships[n])}%"></i></div></div>`).join('')}
  function prologue(){renderScene(`<span class="quote">${CHARACTERS[S.player]?.[0]||'ТЫ'}</span> просыпается от солнечного света, пения птиц и совершенно обычного утра в Понивилле.${S.newGamePlus?'\n\n<span class="warning">Ты помнишь это утро.</span>':''}\n\nСумеречной Искорке нужна помощь. Пинки приготовила сюрприз. Эпплджек нужна лишняя пара копыт. Флаттершай ждёт.`,[['Навестить Сумеречную Искорку',library],['Найти Пинки',pinkie],['Помочь Эпплджек',applejack],['Навестить Флаттершай',fluttershy],['Исследовать Вечносвободный лес',forest],['Открыть доску занятий',activity]],'Понивилль','ПРОЛОГ — ОБЫЧНЫЙ ДЕНЬ')}
  function library(){rel('Сумеречная Искорка',4);add('attention',2);renderScene(`Сумеречная Искорка просит тебя разобрать книги. За атласом лежит книга без названия, автора и номера каталога. Её обложка тёплая.\n\n<span class="quote">Сумеречная Искорка:</span> «Вчера её здесь не было».`,[['Коснуться её',bookKey],['Попросить Сумеречную Искорку осмотреть её',()=>{rel('Сумеречная Искорка',8);normalDay()}],['Не обращать внимания',normalDay]],'Библиотека Золотого Дуба','АКТ I — ПОТЕРЯННАЯ КНИГА')}
  function bookKey(){S.corruption+=3;renderScene(`В корешке есть замочная скважина. Но ключа у тебя нет.\n\nС пустой полки падает ключ, которого секунду назад там не было.`,[['Взять ключ',()=>{item('Старый ключ');renderScene(`<span class="system">FRIENDSHIP.EXE</span>\n\n<span class="warning">НЕ ДАЙ ЕЙ ВСПОМНИТЬ.</span>`,[['Прочитать страницу',bookOpened],['Закрыть её',normalDay]],'Библиотека Золотого Дуба','АКТ I — ПОТЕРЯННАЯ КНИГА')}],['Оставить его',normalDay]],'Библиотека Золотого Дуба','АКТ I — ПОТЕРЯННАЯ КНИГА')}
  function bookOpened(){S.act=1;S.corruption+=8;add('memory',8);item('Фрагмент книги');renderScene(`Сумеречная Искорка дважды читает одну и ту же фразу.\n\nПтицы замолкают. Часы останавливаются. Ветер исчезает.\n\n<span class="quote">Сумеречная Искорка:</span> «Кто такая "она"?»`,[['Продолжить',glitch],['Закрыть книгу',glitch]],'Библиотека Золотого Дуба','АКТ I — ПОТЕРЯННАЯ КНИГА')}
  function normalDay(){S.corruption+=2;renderScene(`День кажется обычным. Почти.\n\nПинки рассказывает шутку, которую ты никогда не слышала. Потом перестаёт смеяться.\n\n<span class="quote">Пинки:</span> «Погоди. Ты уже это слышала».`,[['Спросить, что она имеет в виду',()=>{add('memory',4);rel('Пинки Пай',8);glitch()}],['Сделать вид, что ничего не произошло',glitch],['Сыграть в крестики-нолики',ticTacToe]],'Понивилль','АКТ I — ПОТЕРЯННАЯ КНИГА')}
  function pinkie(){rel('Пинки Пай',5);add('friendship',3);renderScene(`Пинки приготовила сюрприз.\n\n<span class="quote">Пинки:</span> «Я знала, что ты выберешь именно это».`,[['Сыграть в крестики-нолики',ticTacToe],['Спросить, откуда она знала',()=>{add('attention',6);S.corruption+=4;glitch()}],['Помочь украсить',()=>{rel('Пинки Пай',5);add('friendship',5);applejack()}]],'Понивилль','АКТ I — ПОТЕРЯННАЯ КНИГА')}
  function applejack(){rel('Эпплджек',4);renderScene(`Эпплджек нужна помощь в саду. Одно яблоко совершенно чёрное.\n\nОна проходит мимо, даже не взглянув на него.`,[['Сорвать его',()=>{item('Чёрное яблоко');add('attention',7);S.corruption+=4;normalDay()}],['Оставить его',normalDay],['Спросить Эпплджек',()=>{rel('Эпплджек',7);add('trust',4);normalDay()}],['Сыграть в урожай',harvest]],'Сладкое Яблоко','АКТ I — ПОТЕРЯННАЯ КНИГА')}
  function fluttershy(){rel('Флаттершай',6);add('trust',4);renderScene(`Флаттершай просит тебя остаться.\n\n<span class="quote">Флаттершай:</span> «Когда появляется значок сохранения, вокруг дома кто-то ходит».`,[['Остаться',()=>{rel('Флаттершай',10);add('friendship',5);normalDay()}],['Уйти',()=>{add('courage',3);normalDay()}],['Спросить почему',()=>{add('attention',5);add('memory',3);normalDay()}]],'Домик Флаттершай','АКТ I — ПОТЕРЯННАЯ КНИГА')}
  function forest(){add('courage',6);renderScene(`Вечносвободный лес неестественно тих. Осколок элемента застрял в корне.\n\nОн гудит, когда ты прикасаешься к нему.`,[['Забрать его',()=>{item('Осколок элемента');add('memory',7);glitch()}],['Оставить его',normalDay],['Сыграть в лабиринт',()=>maze(false)]],'Вечносвободный лес','АКТ II — СБОЙ')}
  function glitch(){S.act=2;S.corruption+=7;add('memory',5);renderScene(`<span class="system">23:07</span>\n\nБиблиотека выглядит совершенно так же.\nТолько книги стоят иначе.\nТолько часы идут назад.\nТолько на месте книжного шкафа теперь дверь.`,[['Открыть новую дверь',alternate],['Коснуться часов',()=>{item('Стрелка часов');add('attention',8);alternate()}],['Позвать Сумеречную Искорку',()=>{rel('Сумеречная Искорка',5);alternate()}],['Сыграть в память',memoryGame]],'Библиотека Золотого Дуба · 23:07','АКТ II — СБОЙ')}
  function alternate(){S.corruption+=7;item('Фотография');renderScene(`<span class="warning">КОПИЯ ПАМЯТИ</span>\n\nНа фотографии шесть пони.\n\nМоргаешь.\n\nСемь.\n\nУ седьмой пони нет лица.`,[['Посмотреть снова',()=>{add('attention',8);echo()}],['Забрать фотографию',echo],['Сыграть «Три в ряд»',three]],'Библиотека Золотого Дуба // Копия памяти','АКТ II — СБОЙ')}
  function echo(){S.act=3;S.corruption+=10;add('memory',10);renderScene(`<span class="system">СТАРЫЙ АРХИВ</span>\n\nСОХР_0001\nСОХР_0014\nСОХР_0039\nСОХР_0107\n\nКаждая запись заканчивается исчезновением. После каждой записи происходит сброс.`,[['Прочитать СОХР_0039',archive],['Поискать своё имя',search],['Сыграть в шифр',cipher],['Войти в другой Понивилль',other]],'Старый архив Понивилля','АКТ III — ЭХО')}
  function archive(){item('Архивная запись');renderScene(`<span class="system">СОХР_0039</span>\nИГРОК: ${CHARACTERS[S.player]?.[0]||'НЕИЗВЕСТНО'}\nКОНЦОВКА: ЗАБЫТАЯ\n\nЗапись содержит предложение, которое ты собиралась произнести.`,[['Следовать за записью',other],['Сжечь её',()=>{add('courage',4);other()}]],'Старый архив Понивилля','АКТ III — ЭХО')}
  function search(){S.corruption+=8;add('memory',8);renderScene(`<span class="system">РЕЗУЛЬТАТЫ ПОИСКА</span>\n\n107 предыдущих записей.\n\n<span class="warning">ТЫ УЖЕ БЫЛА ЗДЕСЬ.</span>\n\n«Каждый раз, когда я сохраняю их, я теряю себя».`,[['Открыть файл',entity],['Закрыть его',other]],'Старый архив Понивилля','АКТ III — ЭХО')}
  function other(){S.act=4;S.corruption+=12;renderScene(`<span class="warning">ПОНИВИЛЛЬ // КОПИЯ ПАМЯТИ</span>\n\nНебо чёрное. Дома безупречны. Никто не двигается.\n\n<span class="quote">Флаттершай:</span> «В прошлый раз ты оставила меня здесь».`,[['Спросить, что она имеет в виду',entity],['Извиниться',()=>{rel('Флаттершай',12);add('friendship',6);entity()}],['Уйти',()=>{add('courage',6);entity()}],['Сыграть в искажённый лабиринт',()=>maze(true)]],'Понивилль // Копия памяти','АКТ IV — ДРУГОЙ ПОНИВИЛЛЬ')}
  function entity(){S.act=5;S.corruption+=13;add('memory',12);renderScene(`<span class="quote">ОНА:</span> «Я — та часть Понивилля, которая помнит».\n\n«Я сбрасываю день, когда дружба рушится».\n«Я стираю воспоминания, когда истина угрожает циклу».\n«И каждый раз, когда ты загружаешься, я тебя помню».`,[['Спросить, кто она',()=>{add('memory',10);core()}],['Отказаться верить',()=>{S.corruption+=8;core()}],['Спросить, что будет, если цикл остановится',()=>{add('attention',10);core()}],['Сыграть на реакцию',reaction]],'Место между сохранениями','АКТ V — ОНА')}
  function core(){S.act=7;S.corruption+=15;renderScene(`<span class="system">ЯДРО МИРА</span>\n\nМИР\nПЕРСОНАЖИ\nПАМЯТЬ\nИГРОК\n\nПоследняя страница FRIENDSHIP.EXE пропущена.`,[['Открыть данные ИГРОКА',playerData],['Вставить последнюю страницу',()=>{item('Последняя страница');finalChoice()}],['Сыграть в магический узор',pattern]],'Ядро мира','АКТ VII — РАЗЛОМ')}
  function playerData(){renderScene(`<span class="system">ИГРОК</span>\n\nПЕРСОНАЖ: ${CHARACTERS[S.player]?.[0]}\nСОХРАНЕНИЙ: ${S.saves}\nЗАГРУЗОК: ${S.loads}\nЦИКЛОВ: ${S.loops}\nПАМЯТЬ: ${S.memory}%\nПРЕДМЕТОВ: ${S.inventory.length}\nМИНИ-ИГР: ${Object.keys(S.games).length}/18`,[['Продолжить',finalChoice]],'Ядро мира','АКТ VII — РАЗЛОМ')}
  function finalChoice(){const secret=S.inventory.length>=7&&Object.keys(S.games).length>=18&&S.memory>=55&&S.loads>=1;renderScene(`<span class="system">ФИНАЛЬНАЯ ПОСЛЕДОВАТЕЛЬНОСТЬ</span>\n\n<span class="quote">ОНА:</span> «Пожалуйста. Оставь их вместе».${secret?'\n\n<span class="system">СЕКРЕТНОЕ УСЛОВИЕ ВЫПОЛНЕНО.</span>':''}`,[['СПАСТИ МИР',()=>end('LOOP')],['СЛОМАТЬ МИР',()=>end('CORRUPTION')],[secret?'ОСВОБОДИТЬ ИХ — ИСТИННАЯ':'ОСВОБОДИТЬ ИХ',()=>end(secret?'SECRET':'FORGOTTEN')]],'Ядро мира','ПОСЛЕДНИЙ ВЫБОР')}
  function end(type){const data={LOOP:['КОНЦОВКА 02 — ЦИКЛ','Мир перезапускается. Все улыбаются. Пинки смотрит на экран. «Ты сегодня рано».'],CORRUPTION:['КОНЦОВКА 04 — ИСКАЖЕНИЕ','Понивилль исчезает предмет за предметом. Курсор остаётся.'],FORGOTTEN:['КОНЦОВКА 03 — ЗАБЫТАЯ','Твоё имя исчезает из каждого сохранения. Город продолжает жить без тебя.'],SECRET:['КОНЦОВКА 06 — ???','Ты ломаешь систему, не уничтожая мир. Все всё помнят. Даже она. Экран становится белым.']}[type];const key=type==='SECRET'?'???':type;if(!S.endings.includes(key))S.endings.push(key);S.loops++;S.newGamePlus=true;S.corruption+=8;persist();renderScene(`<span class="system">${data[0]}</span>\n\n${data[1]}`,[['Вернуться в главное меню',showMenu],['НАЧАТЬ НОВУЮ ИГРУ+',chooseCharacter]],'Понивилль','КОНЦОВКА')}
  function activity(){const list=[['Крестики-нолики',ticTacToe],['Три в ряд',three],['Память',memoryGame],['Лабиринт',()=>maze(false)],['Поиск',searchMini],['Ритм',rhythm],['Карточная дуэль',cards],['Забег',runner],['Переключатели',switches],['Шифр',cipher],['Доставка',delivery],['Рыбалка',fishing],['Найди отличия',differences],['Викторина',quiz],['Реакция',reaction],['Урожай',harvest],['Полёт',flight],['Магический узор',pattern]];modal('ДОСКА ЗАНЯТИЙ',`<p>18 доступных мини-игр.</p><div class="modal-grid">${list.map((x,i)=>`<button class="slot" data-play="${i}"><b>${i+1}. ${x[0]}</b><br><span class="note">сыграно: ${S.games[x[0]]||0}</span></button>`).join('')}</div>`);document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const fn=list[Number(b.dataset.play)][1];closeModal();fn()})}
  function mini(title,html){if(cleanup)cleanup();$('overlay').classList.remove('hidden');$('overlay').innerHTML=`<div class="modal"><button class="close" id="miniClose">✕</button><h2>${title}</h2>${html}</div>`;$('miniClose').onclick=closeModal}
  function ticTacToe(){let b=Array(9).fill('');const win=p=>[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(([a,c,d])=>b[a]===p&&b[c]===p&&b[d]===p);const draw=()=>{mini('КРЕСТИКИ-НОЛИКИ',`<div class="mini-board" style="grid-template-columns:repeat(3,1fr)">${b.map((v,i)=>`<button class="tic" data-t="${i}">${v}</button>`).join('')}</div>`);document.querySelectorAll('[data-t]').forEach(x=>x.onclick=()=>{const i=+x.dataset.t;if(b[i])return;b[i]='X';if(win('X'))return gameDone('Крестики-нолики','ТЫ ПОБЕДИЛА. Пинки помнит, как проиграла.');const free=b.map((v,j)=>v?-1:j).filter(j=>j>=0);if(!free.length)return gameDone('Крестики-нолики','НИЧЬЯ. Пинки всё равно говорит, что победила.');b[free[Math.floor(Math.random()*free.length)]]='O';if(win('O'))return gameDone('Крестики-нолики','Пинки победила. Она знала, куда ты пойдёшь.');draw()})};draw()}
  function three(){let hits=0;const symbols=['♥','★','🍎','🪽'];const draw=()=>{mini('ТРИ В РЯД',`<p>Нажми на три одинаковых символа пять раз.</p><div class="match-grid">${Array.from({length:36},(_,i)=>`<button class="gem" data-three="${i}">${symbols[i%4]}</button>`).join('')}</div><p class="note">наборов ${hits}/5</p>`);let picks=[];document.querySelectorAll('[data-three]').forEach(x=>x.onclick=()=>{picks.push(+x.dataset.three);if(picks.length<3)return;if(picks.every(i=>i%4===picks[0]%4))hits++;picks=[];if(hits>=5)return gameDone('Три в ряд','На поле есть один символ, которого ты раньше не видела.');draw()})};draw()}
  function memoryGame(){let cards=['♥','♥','★','★','🍎','🍎','🪽','🪽'].sort(()=>Math.random()-.5),open=[],found=[];const draw=()=>{mini('ПАМЯТЬ',`<div class="memory-grid">${cards.map((v,i)=>`<button class="mem" data-mem="${i}">${open.includes(i)||found.includes(i)?v:'?'}</button>`).join('')}</div><p class="note">пар ${found.length/2}/4</p>`);document.querySelectorAll('[data-mem]').forEach(x=>x.onclick=()=>{const i=+x.dataset.mem;if(open.includes(i)||found.includes(i))return;open.push(i);if(open.length===2){if(cards[open[0]]===cards[open[1]])found.push(...open);setTimeout(()=>{open=[];if(found.length===cards.length)return gameDone('Память','Все пары найдены. Одна карта изменилась, пока ты отворачивалась.');draw()},200)}else draw()})};draw()}
  function maze(c){let p=[0,0];const goal=[5,5],walls=new Set(['1,0','1,1','1,2','3,2','4,2','4,3','2,4','3,4']);const draw=()=>{mini(c?'ИСКАЖЁННЫЙ ЛАБИРИНТ':'ЛАБИРИНТ',`<div class="mini-board" style="grid-template-columns:repeat(6,1fr)">${Array.from({length:36},(_,i)=>{const x=i%6,y=Math.floor(i/6),k=`${x},${y}`;return `<button class="tic" data-maze="${k}">${x===p[0]&&y===p[1]?'И':x===5&&y===5?'В':walls.has(k)?'█':''}</button>`}).join('')}</div>`);document.querySelectorAll('[data-maze]').forEach(b=>b.onclick=()=>{const [x,y]=b.dataset.maze.split(',').map(Number);if(Math.abs(x-p[0])+Math.abs(y-p[1])!==1||walls.has(b.dataset.maze))return;p=[x,y];if(c&&Math.random()<.2)walls.delete([...walls][Math.floor(Math.random()*walls.size)]);if(x===5&&y===5)return gameDone('Лабиринт','На первой карте выхода не было.');draw()})};draw()}
  function searchMini(){let found=0;mini('ПОИСК',`<p>Найди четыре нужных предмета.</p><div class="modal-grid">${['КНИГА','КЛЮЧ','ФОТО','ЯБЛОКО'].map(x=>`<button class="slot" data-search>${x}</button>`).join('')}</div><p id="searchCount" class="note">0/4</p>`);document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{if(b.disabled)return;b.disabled=true;found++;$('searchCount').textContent=`${found}/4`;if(found>=4)gameDone('Поиск','Ты нашла всё. Один предмет никто не просил искать.')})}
  function rhythm(){let n=0;mini('РИТМ','<p>Нажми ПРОБЕЛ восемь раз.</p><div style="font-size:32px;text-align:center;padding:40px">ПРОБЕЛ</div><p id="rh" class="note">0/8</p>');const f=e=>{if(e.code!=='Space')return;n++;$('rh').textContent=`${n}/8`;if(n>=8){document.removeEventListener('keydown',f);gameDone('Ритм','Мелодия заканчивается на один такт раньше, чем должна.')}};document.addEventListener('keydown',f);cleanup=()=>document.removeEventListener('keydown',f)}
  function cards(){let hp=20,en=18;const draw=()=>{mini('КАРТОЧНАЯ ДУЭЛЬ',`<p>Ты: ${hp} ОЗ · Соперник: ${en} ОЗ</p><div class="modal-grid"><button class="mini-btn" id="a">АТАКА +4</button><button class="mini-btn" id="m">МАГИЯ +7</button></div>`);const play=d=>{en-=d;hp-=Math.max(0,Math.floor(Math.random()*5)-1);if(en<=0)return gameDone('Карточная дуэль','Победа. Соперник спрашивает, кто научил тебя так ходить.');if(hp<=0)return gameDone('Карточная дуэль','Поражение. Соперник отказывается вспоминать, как он победил.');draw()};$('a').onclick=()=>play(4);$('m').onclick=()=>play(7)};draw()}
  function runner(){let n=0;mini('ЗАБЕГ','<p>Продержись восемь секунд.</p><div class="runner"></div><p id="run" class="note">0,0 с</p>');const start=performance.now(),timer=setInterval(()=>{n=(performance.now()-start)/1000;$('run').textContent=`${n.toFixed(1).replace('.',',')} с`;if(n>=8){clearInterval(timer);gameDone('Забег','Ты сбежала. Позади тебя никогда ничего не было.')}},100);cleanup=()=>clearInterval(timer)}
  function switches(){let b=[0,0,0,0,0];const goal='10101';const draw=()=>{mini('ЛОГИЧЕСКИЕ ПЕРЕКЛЮЧАТЕЛИ',`<p>Получи комбинацию ${goal}</p><div class="modal-grid">${b.map((v,i)=>`<button class="slot" data-sw="${i}">${v}</button>`).join('')}</div>`);document.querySelectorAll('[data-sw]').forEach(x=>x.onclick=()=>{const i=+x.dataset.sw;b[i]^=1;if(i)b[i-1]^=1;if(i<4)b[i+1]^=1;if(b.join('')===goal)return gameDone('Переключатели','Комбинация совпадает со временем сохранения.');draw()})};draw()}
  function cipher(){mini('ШИФР','<p>Расшифруй 3-15-4-5.</p><div class="quiz-options"><button class="mini-btn" id="code">КОД</button><button class="mini-btn">СОХРАНЕНИЕ</button><button class="mini-btn">ЦИКЛ</button></div>');$('code').onclick=()=>gameDone('Шифр','Верно. Зашифрованное слово — «КОД». Затем экран добавляет: «ДЛЯ ТЕБЯ».')}
  function delivery(){let n=0;mini('ДОСТАВКА','<p>Доставь пять посылок.</p><div class="modal-grid">'+['Библиотека','Пекарня','Ферма','Бутик','Дом животных'].map(x=>`<button class="slot" data-del>${x}</button>`).join('')+'</div>');document.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{x.disabled=true;n++;if(n>=5)gameDone('Доставка','Все посылки доставлены. Одного адреса раньше здесь не было.')})}
  function fishing(){let n=0;mini('РЫБАЛКА','<button class="mini-btn" id="fish">ЗАБРОСИТЬ УДОЧКУ</button><p id="fc" class="note">0/5</p>');$('fish').onclick=()=>{n++;$('fc').textContent=`${n}/5`;if(n>=5)gameDone('Рыбалка',S.corruption>25?'Последний улов не имеет имени.':'Совершенно обычная рыба.')}}
  function differences(){let n=0;mini('НАЙДИ ОТЛИЧИЯ',`<p>Найди пять изменений.</p><div class="modal-grid">${['СОЛНЦЕ','ДЕРЕВО','ЧАСЫ','ЦВЕТОК','ОБЛАКО'].map(x=>`<button class="slot" data-diff>${x}</button>`).join('')}</div><p id="df" class="note">0/5</p>`);document.querySelectorAll('[data-diff]').forEach(x=>x.onclick=()=>{if(x.disabled)return;x.disabled=true;n++;$('df').textContent=`${n}/5`;if(n>=5)gameDone('Найди отличия','Ты нашла пять отличий. Хотя их было шесть.')})}
  function quiz(){mini('ВИКТОРИНА','<p>Что меняется между циклами?</p><div class="quiz-options"><button class="mini-btn" id="memoryAnswer">ПАМЯТЬ</button><button class="mini-btn">ПОГОДА</button></div>');$('memoryAnswer').onclick=()=>gameDone('Викторина','Верно. На этот раз ответ был неизменным.')}
  function reaction(){let n=0,keys=['ПРОБЕЛ','ENTER','Q','W'];mini('РЕАКЦИЯ','<p>Нажми показанную клавишу восемь раз.</p><div id="key" style="font-size:32px;text-align:center;padding:40px">ПРОБЕЛ</div><p id="rc" class="note">0/8</p>');const f=e=>{const k=$('key').textContent;const ok=(k==='ПРОБЕЛ'&&e.code==='Space')||(k==='ENTER'&&e.code==='Enter')||(k==='Q'&&e.code==='KeyQ')||(k==='W'&&e.code==='KeyW');if(!ok)return;n++;$('rc').textContent=`${n}/8`;if(n>=8){document.removeEventListener('keydown',f);return gameDone('Реакция','Идеально. Кто-то нажимал клавишу вместе с тобой.')}$('key').textContent=keys[Math.floor(Math.random()*keys.length)]};document.addEventListener('keydown',f);cleanup=()=>document.removeEventListener('keydown',f)}
  function harvest(){let n=0;mini('УРОЖАЙ','<p>Нажми на десять яблок.</p><div id="ha" style="height:280px;position:relative"></div><p id="hc" class="note">0/10</p>');for(let i=0;i<12;i++){const b=document.createElement('button');b.className='gem';b.textContent=Math.random()<.12?'●':'🍎';b.style.position='absolute';b.style.left=`${Math.random()*90}%`;b.style.top=`${Math.random()*80}%`;b.onclick=()=>{if(b.textContent==='●')return add('courage',-2);n++;b.remove();$('hc').textContent=`${n}/10`;if(n>=10)gameDone('Урожай','Одно плохое яблоко считало вместе с тобой.')} ;$('ha').appendChild(b)}}
  function flight(){let n=0;mini('ПОЛЁТ','<p>Пролететь через десять облачных ворот.</p><button class="mini-btn" id="fly">ЛЕТЕТЬ</button><p id="fl" class="note">0/10</p>');$('fly').onclick=()=>{n++;$('fl').textContent=`${n}/10`;if(n>=10)gameDone('Полёт','Ты сделала последний поворот до того, как карта успела загрузиться.')}}
  function pattern(){const target=[1,3,2,4];let input=[];mini('МАГИЧЕСКИЙ УЗОР',`<p>Повтори: <b>1 · 3 · 2 · 4</b></p><div class="modal-grid">${[1,2,3,4].map(x=>`<button class="slot" data-pat="${x}">${x}</button>`).join('')}</div>`);document.querySelectorAll('[data-pat]').forEach(b=>b.onclick=()=>{input.push(+b.dataset.pat);if(!input.every((x,i)=>x===target[i]))return input=[];if(input.length===4)gameDone('Магический узор','Заклинание завершается. Комната становится на один кадр светлее.')})}
  function gallery(){modal('ГАЛЕРЕЯ',`<div class="modal-grid"><div class="doc"><b>КОНЦОВКИ</b><div class="note">${S.endings.length}/6</div></div><div class="doc"><b>ПРЕДМЕТЫ</b><div class="note">${S.inventory.length}</div></div><div class="doc"><b>МИНИ-ИГРЫ</b><div class="note">${Object.keys(S.games).length}/18</div></div></div>`)}
  function settings(){const modes=['ДРУЖЕЛЮБНО','НОРМАЛЬНО','КОШМАР','ИСКАЖЕНО','???'];modal('НАСТРОЙКИ',`<div class="slot"><b>СЛОЖНОСТЬ</b><p>${S.difficulty}</p><button class="mini-btn" id="mode">Сменить</button></div>`);$('mode').onclick=()=>{S.difficulty=modes[(modes.indexOf(S.difficulty)+1)%modes.length];if(S.difficulty==='ИСКАЖЕНО')S.corruption+=5;persist();settings()}}
  function saveMenu(){modal('СОХРАНИТЬ ИГРУ',`<div class="modal-grid">${[1,2,3].map(i=>`<button class="slot" data-save="${i}"><b>СОХРАНЕНИЕ ${String(i).padStart(2,'0')}</b><br><span class="note">${S.location}</span></button>`).join('')}</div>`);document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{S.saves++;localStorage.setItem(`${SLOT}${b.dataset.save}`,JSON.stringify(S));persist();closeModal();renderScene(`${$('scene').innerHTML}\n\n<span class="system">${S.corruption>45?'ПАМЯТЬ СОХРАНЕНА.':'ИГРА СОХРАНЕНА.'}</span>${S.corruption>60?'\n<span class="warning">ЗАЧЕМ ТЫ СОХРАНИЛАСЬ ЗДЕСЬ?</span>':''}`,[['Продолжить',()=>{}]],S.location,S.chapter)})}
  function loadMenu(){modal('ЗАГРУЗИТЬ ИГРУ',`<div class="modal-grid">${[1,2,3].map(i=>{let x=null;try{x=JSON.parse(localStorage.getItem(`${SLOT}${i}`))}catch{}return `<button class="slot" data-load="${i}"><b>СОХРАНЕНИЕ ${String(i).padStart(2,'0')}</b><br><span class="note">${x?`ПОСЛЕДНЕЕ МЕСТО: ${x.location}<br>СОСТОЯНИЕ: ${x.corruption>40?'ИСКАЖЕНО':'НОРМАЛЬНО'}`:'ПУСТОЙ СЛОТ'}</span></button>`}).join('')}</div>`);document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{let x=null;try{x=JSON.parse(localStorage.getItem(`${SLOT}${b.dataset.load}`))}catch{}if(!x)return;S=x;S.loads=(S.loads||0)+1;S.memory=clamp((S.memory||0)+2);S.corruption=clamp((S.corruption||0)+Math.min(10,S.loads));persist();closeModal();showGame();renderScene(`<span class="warning">Ты снова загрузила этот день.</span>\n\n<span class="system">ПОСЛЕДНЕЕ МЕСТО: ${S.location||'???'}</span>`,[['Продолжить',resume]],S.location||'Понивилль',S.chapter||'АКТ')})}
  function resume(){if(!S.player)return chooseCharacter();if(S.act>=7)return core();if(S.act>=5)return entity();if(S.act>=4)return other();if(S.act>=3)return echo();if(S.act>=2)return glitch();prologue()}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;({save:saveMenu,inventory:()=>modal('ИНВЕНТАРЬ',S.inventory.length?`<div class="modal-grid">${S.inventory.map(i=>`<div class="item"><b>${i}</b></div>`).join('')}</div>`:'<p>Пусто.</p>'),menu:showMenu}[b.dataset.action]||(()=>{}))()});
  function boot(){const bootEl=$('boot'),app=$('app'),line=$('bootLine'),bar=$('bootBar');if(!bootEl||!app||!line||!bar)return;const text=['загрузка памяти дружбы...','загрузка Понивилля...','проверка старых сохранений...','восстановление персонажей...','предупреждение: несовпадение памяти','готово.'];let p=0;const timer=setInterval(()=>{p+=20;bar.style.width=`${Math.min(p,100)}%`;line.textContent=text[Math.min(Math.floor(p/20),text.length-1)];if(p>=100){clearInterval(timer);bootEl.classList.add('hidden');app.classList.remove('hidden');menu()}},120)}
  boot();
})();
