(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const KEY = 'the-last-save-browser-v1';
  const SLOT = `${KEY}:slot:`;
  const CHARACTERS = {twilight:['TWILIGHT','MAGIC'],fluttershy:['FLUTTERSHY','EMPATHY'],pinkie:['PINKIE PIE','CHAOS'],applejack:['APPLEJACK','HARVEST'],rarity:['RARITY','FOCUS'],rainbow:['RAINBOW DASH','SPEED']};
  const NPCS = ['Twilight','Fluttershy','Pinkie Pie','Applejack','Rarity','Rainbow Dash'];
  const initial = () => ({player:null,act:0,scene:'prologue',location:'Ponyville',chapter:'PROLOGUE — AN ORDINARY DAY',friendship:15,courage:15,attention:15,trust:15,memory:0,corruption:0,saves:0,loads:0,loops:0,inventory:[],endings:[],games:{},visits:{},difficulty:'NORMAL',newGamePlus:false,relationships:Object.fromEntries(NPCS.map(n=>[n,20]))});
  let S = readState();
  let cleanup = null;
  function readState(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&typeof x==='object'?x:initial()}catch{return initial()}}
  function persist(){localStorage.setItem(KEY,JSON.stringify(S))}
  function clamp(x){return Math.max(0,Math.min(100,Math.round(Number(x)||0)))}
  function add(k,n){S[k]=clamp((S[k]||0)+n)}
  function rel(n,nr){S.relationships[n]=clamp((S.relationships[n]||0)+nr)}
  function item(n){if(!S.inventory.includes(n))S.inventory.push(n)}
  function gameDone(n,msg){S.games[n]=(S.games[n]||0)+1;add('friendship',2);add('memory',1);persist();const m=$('overlay').querySelector('.modal');m.insertAdjacentHTML('beforeend',`<p>${msg}</p><button class="mini-btn" id="continueMini">Continue</button>`);$('continueMini').onclick=closeModal}
  function showGame(){ $('menu').classList.add('hidden'); $('game').classList.remove('hidden') }
  function showMenu(){ $('game').classList.add('hidden'); $('menu').classList.remove('hidden'); menu() }
  function menu(){const label=S.corruption>65?'YOU ALREADY PLAYED THIS.':S.corruption>30?'RESTART':'NEW GAME';$('menu').innerHTML=`<div class="menu-card"><h1 class="title">MY LITTLE PONY:<br>THE LAST SAVE</h1><div class="subtitle">Friendship was never deleted.</div><div class="menu-buttons"><button class="menu-btn" id="newGame">${label}<span class="small">begin another ordinary day</span></button><button class="menu-btn" id="loadGame">LOAD GAME<span class="small">the saves remember more than you do</span></button><button class="menu-btn" id="gallery">GALLERY<span class="small">${S.endings.length}/6 endings</span></button><button class="menu-btn" id="settings">SETTINGS<span class="small">difficulty · accessibility</span></button><button class="menu-btn" id="about">ABOUT<span class="small">memory horror story</span></button></div><div class="footer">browser edition · local saves · 18 mini-games</div></div>`;$('newGame').onclick=chooseCharacter;$('loadGame').onclick=loadMenu;$('gallery').onclick=gallery;$('settings').onclick=settings;$('about').onclick=()=>modal('ABOUT','<p><b>THE LAST SAVE</b> is a browser horror adventure about memory, repetition and a world that refuses to change.</p>')}
  function modal(title,html){$('overlay').classList.remove('hidden');$('overlay').innerHTML=`<div class="modal"><button class="close" id="modalClose">✕</button><h2>${title}</h2>${html}</div>`;$('modalClose').onclick=closeModal}
  function closeModal(){if(cleanup){cleanup();cleanup=null}$('overlay').classList.add('hidden');$('overlay').innerHTML=''}
  function chooseCharacter(){const html=Object.entries(CHARACTERS).map(([id,c])=>`<button class="slot" data-char="${id}"><b>${c[0]}</b><br><span class="note">SPECIALTY: ${c[1]}</span></button>`).join('');modal('CHOOSE YOUR CHARACTER',`<p>Choose who enters the first loop.</p><div class="modal-grid">${html}</div>`);document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{const old=S;S=initial();S.player=b.dataset.char;S.loops=old.loops||0;S.endings=Array.isArray(old.endings)?old.endings:[];S.difficulty=old.difficulty||'NORMAL';S.newGamePlus=!!old.newGamePlus;S.memory=S.newGamePlus?clamp(old.memory+15):0;S.corruption=S.newGamePlus?Math.max(0,clamp(old.corruption)-10):0;if(S.newGamePlus)add('attention',20);persist();closeModal();showGame();prologue()})}
  function renderScene(text,choices,location=S.location,chapter=S.chapter){S.location=location;S.chapter=chapter;S.visits[location]=(S.visits[location]||0)+1;persist();$('chapterLabel').textContent=chapter;$('clockLabel').textContent=S.corruption>=40?'23:07':'09:14';$('locationTitle').textContent=location;$('scene').innerHTML=text.replace(/\n/g,'<br>');$('choices').innerHTML=choices.map((c,i)=>`<button class="choice-btn" data-choice="${i}"><strong>${i+1}.</strong> ${c[0]}</button>`).join('');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choices[Number(b.dataset.choice)][1]());document.body.classList.toggle('corrupted',S.corruption>=55);hud()}
  function hud(){const c=CHARACTERS[S.player];$('portrait').textContent=c?c[0][0]:'?';$('playerName').textContent=c?`${c[0]} · ${c[1]}`:'NOT SELECTED';const stats=[['FRIENDSHIP',S.friendship],['COURAGE',S.courage],['ATTENTION',S.attention],['TRUST',S.trust],['MEMORY',S.memory]];$('stats').innerHTML=stats.map(([n,v])=>`<div class="stat"><b><span>${n}</span><span>${clamp(v)}</span></b><div class="bar"><i style="width:${clamp(v)}%"></i></div></div>`).join('');$('relationships').innerHTML=NPCS.map(n=>`<div class="rel"><b><span>${n}</span><span>${clamp(S.relationships[n])}%</span></b><div class="bar"><i style="width:${clamp(S.relationships[n])}%"></i></div></div>`).join('')}
  function prologue(){renderScene(`<span class="quote">${CHARACTERS[S.player]?.[0]||'YOU'}</span> wakes to sunlight, birdsong and a perfectly ordinary Ponyville morning.${S.newGamePlus?'\n\n<span class="warning">You remember this morning.</span>':''}\n\nTwilight needs help. Pinkie has a surprise. Applejack needs a hoof. Fluttershy is waiting.`,[['Visit Twilight',library],['Find Pinkie',pinkie],['Help Applejack',applejack],['Visit Fluttershy',fluttershy],['Explore Everfree Forest',forest],['Open Activity Board',activity]],'Ponyville','PROLOGUE — AN ORDINARY DAY')}
  function library(){rel('Twilight',4);add('attention',2);renderScene(`Twilight asks you to sort books. Behind an atlas is a book with no title, author or catalogue number. Its cover is warm.\n\n<span class="quote">Twilight:</span> “That wasn't there yesterday.”`,[['Touch it',bookKey],['Ask Twilight to inspect it',()=>{rel('Twilight',8);normalDay()}],['Ignore it',normalDay]],'Golden Oak Library','ACT I — THE LOST BOOK')}
  function bookKey(){S.corruption+=3;renderScene(`There is a keyhole in the spine. You do not have a key.\n\nA key falls from a shelf that was empty a moment ago.`,[['Take the key',()=>{item('Old Key');renderScene(`<span class="system">FRIENDSHIP.EXE</span>\n\n<span class="warning">DON'T LET HER REMEMBER.</span>`,[['Read the page',bookOpened],['Close it',normalDay]],'Golden Oak Library','ACT I — THE LOST BOOK')}],['Leave it',normalDay]],'Golden Oak Library','ACT I — THE LOST BOOK')}
  function bookOpened(){S.act=1;S.corruption+=8;add('memory',8);item('Fragment of Book');renderScene(`Twilight reads the sentence twice.\n\nThe birds stop. The clock stops. The wind stops.\n\n<span class="quote">Twilight:</span> “Who is 'her'?”`,[['Continue',glitch],['Close the book',glitch]],'Golden Oak Library','ACT I — THE LOST BOOK')}
  function normalDay(){S.corruption+=2;renderScene(`The afternoon feels normal. Almost.\n\nPinkie tells a joke you have never heard. Then she stops laughing.\n\n<span class="quote">Pinkie:</span> “Wait. You already heard this.”`,[['Ask what she means',()=>{add('memory',4);rel('Pinkie Pie',8);glitch()}],['Pretend nothing happened',glitch],['Play Tic-Tac-Toe',ticTacToe]],'Ponyville','ACT I — THE LOST BOOK')}
  function pinkie(){rel('Pinkie Pie',5);add('friendship',3);renderScene(`Pinkie has prepared a surprise.\n\n<span class="quote">Pinkie:</span> “I knew you would choose this.”`,[['Play Tic-Tac-Toe',ticTacToe],['Ask how she knew',()=>{add('attention',6);S.corruption+=4;glitch()}],['Help decorate',()=>{rel('Pinkie Pie',5);add('friendship',5);applejack()}]])}
  function applejack(){rel('Applejack',4);renderScene(`Applejack needs help in the orchard. One apple is completely black.\n\nShe walks past it without looking.`,[['Pick it',()=>{item('Black Apple');add('attention',7);S.corruption+=4;normalDay()}],['Leave it',normalDay],['Ask Applejack',()=>{rel('Applejack',7);add('trust',4);normalDay()}],['Play Harvest',harvest]],'Sweet Apple Acres','ACT I — THE LOST BOOK')}
  function fluttershy(){rel('Fluttershy',6);add('trust',4);renderScene(`Fluttershy asks you to stay.\n\n<span class="quote">Fluttershy:</span> “Something walks around the house whenever the save icon appears.”`,[['Stay',()=>{rel('Fluttershy',10);add('friendship',5);normalDay()}],['Leave',()=>{add('courage',3);normalDay()}],['Ask why',()=>{add('attention',5);add('memory',3);normalDay()}]],"Fluttershy's Cottage",'ACT I — THE LOST BOOK')}
  function forest(){add('courage',6);renderScene(`The Everfree Forest is unnaturally still. An Element shard is embedded in a root.\n\nIt hums when you touch it.`,[['Take it',()=>{item('Element Shard');add('memory',7);glitch()}],['Leave it',normalDay],['Play Labyrinth',()=>maze(false)]],'Everfree Forest','ACT II — THE GLITCH')}
  function glitch(){S.act=2;S.corruption+=7;add('memory',5);renderScene(`<span class="system">23:07</span>\n\nThe library is identical.\nExcept the books are in a different order.\nExcept the clock moves backward.\nExcept there is a door where a bookshelf should be.`,[['Open the new door',alternate],['Touch the clock',()=>{item('Clock Hand');add('attention',8);alternate()}],['Call Twilight',()=>{rel('Twilight',5);alternate()}],['Play Memory',memoryGame]],'Golden Oak Library · 23:07','ACT II — THE GLITCH')}
  function alternate(){S.corruption+=7;item('Photo');renderScene(`<span class="warning">MEMORY COPY</span>\n\nA photograph shows six ponies.\n\nBlink.\n\nSeven.\n\nThe seventh pony has no face.`,[['Look again',()=>{add('attention',8);echo()}],['Take the photo',echo],['Play Three in a Row',three]],'Golden Oak Library // Memory Copy','ACT II — THE GLITCH')}
  function echo(){S.act=3;S.corruption+=10;add('memory',10);renderScene(`<span class="system">OLD ARCHIVE</span>\n\nSAVE_0001\nSAVE_0014\nSAVE_0039\nSAVE_0107\n\nEvery record ends with a disappearance. Every record is followed by a reset.`,[['Read SAVE_0039',archive],['Search your name',search],['Play Cipher',cipher],['Enter other Ponyville',other]],'Old Ponyville Archive','ACT III — ECHO')}
  function archive(){item('Archive Record');renderScene(`<span class="system">SAVE_0039</span>\nPLAYER: ${CHARACTERS[S.player]?.[0]||'UNKNOWN'}\nEND: FORGOTTEN\n\nThe record contains the sentence you were about to say.`,[['Follow it',other],['Burn it',()=>{add('courage',4);other()}]],'Old Ponyville Archive','ACT III — ECHO')}
  function search(){S.corruption+=8;add('memory',8);renderScene(`<span class="system">SEARCH RESULTS</span>\n\n107 previous records.\n\n<span class="warning">YOU HAVE BEEN HERE BEFORE.</span>\n\n“Every time I save them, I lose myself.”`,[['Open the file',entity],['Close it',other]],'Old Ponyville Archive','ACT III — ECHO')}
  function other(){S.act=4;S.corruption+=12;renderScene(`<span class="warning">PONYVILLE // MEMORY COPY</span>\n\nThe sky is black. The houses are perfect. Nobody moves.\n\n<span class="quote">Fluttershy:</span> “In the last one, you left me here.”`,[['Ask what she means',entity],['Apologize',()=>{rel('Fluttershy',12);add('friendship',6);entity()}],['Leave',()=>{add('courage',6);entity()}],['Play Corrupted Maze',()=>maze(true)]],'Ponyville // Memory Copy','ACT IV — THE OTHER PONYVILLE')}
  function entity(){S.act=5;S.corruption+=13;add('memory',12);renderScene(`<span class="quote">SHE:</span> “I am the part of Ponyville that remembers.”\n\n“I reset the day when friendship breaks.”\n“I erase memories when truth threatens the loop.”\n“And every time you reload, I remember you.”`,[['Ask who she is',()=>{add('memory',10);core()}],['Refuse',()=>{S.corruption+=8;core()}],['Ask what happens if the loop stops',()=>{add('attention',10);core()}],['Play Reaction',reaction]],'The Place Between Saves','ACT V — SHE')}
  function core(){S.act=7;S.corruption+=15;renderScene(`<span class="system">WORLD CORE</span>\n\nWORLD\nCHARACTERS\nMEMORY\nPLAYER\n\nThe last page of FRIENDSHIP.EXE is missing.`,[['Open PLAYER data',playerData],['Insert last page',()=>{item('Last Page');finalChoice()}],['Play Magic Pattern',pattern]],'World Core','ACT VII — THE FRACTURE')}
  function playerData(){renderScene(`<span class="system">PLAYER</span>\n\nCHARACTER: ${CHARACTERS[S.player]?.[0]}\nSAVES: ${S.saves}\nLOADS: ${S.loads}\nLOOPS: ${S.loops}\nMEMORY: ${S.memory}%\nITEMS: ${S.inventory.length}\nMINI-GAMES: ${Object.keys(S.games).length}/18`,[['Continue',finalChoice]],'World Core','ACT VII — THE FRACTURE')}
  function finalChoice(){const secret=S.inventory.length>=7&&Object.keys(S.games).length>=18&&S.memory>=55&&S.loads>=1;renderScene(`<span class="system">FINAL SEQUENCE</span>\n\n<span class="quote">SHE:</span> “Please. Keep them together.”${secret?'\n\n<span class="system">SECRET CONDITION MET.</span>':''}`,[['SAVE THE WORLD',()=>end('LOOP')],['BREAK THE WORLD',()=>end('CORRUPTION')],[secret?'FREE THEM — TRUE':'FREE THEM',()=>end(secret?'SECRET':'FORGOTTEN')]],'World Core','FINAL CHOICE')}
  function end(type){const data={LOOP:['ENDING 02 — LOOP','The world resets. Everyone smiles. Pinkie looks at the screen. “You are early this time.”'],CORRUPTION:['ENDING 04 — CORRUPTION','Ponyville disappears one object at a time. The cursor remains.'],FORGOTTEN:['ENDING 03 — FORGOTTEN','Your name disappears from every save. The town continues without you.'],SECRET:['ENDING 06 — ???','You break the system without destroying the world. Everyone remembers. Even her. The screen goes white.']}[type];const key=type==='SECRET'?'???':type;if(!S.endings.includes(key))S.endings.push(key);S.loops++;S.newGamePlus=true;S.corruption+=8;persist();renderScene(`<span class="system">${data[0]}</span>\n\n${data[1]}`,[['Return to title',showMenu],['START NEW GAME+',chooseCharacter]],'Ponyville','ENDING')}
  function activity(){const list=[['Tic-Tac-Toe',ticTacToe],['Three in a Row',three],['Memory',memoryGame],['Labyrinth',()=>maze(false)],['Search',searchMini],['Rhythm',rhythm],['Card Duel',cards],['Runner',runner],['Switches',switches],['Cipher',cipher],['Delivery',delivery],['Fishing',fishing],['Differences',differences],['Quiz',quiz],['Reaction',reaction],['Harvest',harvest],['Flight',flight],['Magic Pattern',pattern]];modal('ACTIVITY BOARD',`<p>18 playable mini-games.</p><div class="modal-grid">${list.map((x,i)=>`<button class="slot" data-play="${i}"><b>${i+1}. ${x[0]}</b><br><span class="note">played: ${S.games[x[0]]||0}</span></button>`).join('')}</div>`);document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const fn=list[Number(b.dataset.play)][1];closeModal();fn()})}
  function mini(title,html){if(cleanup)cleanup();$('overlay').classList.remove('hidden');$('overlay').innerHTML=`<div class="modal"><button class="close" id="miniClose">✕</button><h2>${title}</h2>${html}</div>`;$('miniClose').onclick=closeModal}
  function ticTacToe(){let b=Array(9).fill('');const win=p=>[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(([a,c,d])=>b[a]===p&&b[c]===p&&b[d]===p);const draw=()=>{mini('TIC-TAC-TOE',`<div class="mini-board" style="grid-template-columns:repeat(3,1fr)">${b.map((v,i)=>`<button class="tic" data-t="${i}">${v}</button>`).join('')}</div>`);document.querySelectorAll('[data-t]').forEach(x=>x.onclick=()=>{const i=+x.dataset.t;if(b[i])return;b[i]='X';if(win('X'))return gameDone('Tic-Tac-Toe','YOU WIN. Pinkie remembers losing.');const free=b.map((v,j)=>v?-1:j).filter(j=>j>=0);if(!free.length)return gameDone('Tic-Tac-Toe','DRAW. Pinkie says she won anyway.');b[free[Math.floor(Math.random()*free.length)]]='O';if(win('O'))return gameDone('Tic-Tac-Toe','Pinkie wins. She knew where you would move.');draw()})};draw()}
  function three(){let hits=0;const symbols=['♥','★','🍎','🪽'];const draw=()=>{mini('THREE IN A ROW',`<p>Click three equal symbols five times.</p><div class="match-grid">${Array.from({length:36},(_,i)=>`<button class="gem" data-three="${i}">${symbols[i%4]}</button>`).join('')}</div><p class="note">sets ${hits}/5</p>`);let picks=[];document.querySelectorAll('[data-three]').forEach(x=>x.onclick=()=>{picks.push(+x.dataset.three);if(picks.length<3)return;if(picks.every(i=>i%4===picks[0]%4))hits++;picks=[];if(hits>=5)return gameDone('Three in a Row','The board contains one symbol you never saw before.');draw()})};draw()}
  function memoryGame(){let cards=['♥','♥','★','★','🍎','🍎','🪽','🪽'].sort(()=>Math.random()-.5),open=[],found=[];const draw=()=>{mini('MEMORY',`<div class="memory-grid">${cards.map((v,i)=>`<button class="mem" data-mem="${i}">${open.includes(i)||found.includes(i)?v:'?'}</button>`).join('')}</div><p class="note">pairs ${found.length/2}/4</p>`);document.querySelectorAll('[data-mem]').forEach(x=>x.onclick=()=>{const i=+x.dataset.mem;if(open.includes(i)||found.includes(i))return;open.push(i);if(open.length===2){if(cards[open[0]]===cards[open[1]])found.push(...open);setTimeout(()=>{open=[];if(found.length===cards.length)return gameDone('Memory','All pairs found. One card changed while you looked away.');draw()},200)}else draw()})};draw()}
  function maze(c){let p=[0,0];const goal=[5,5],walls=new Set(['1,0','1,1','1,2','3,2','4,2','4,3','2,4','3,4']);const draw=()=>{mini(c?'CORRUPTED MAZE':'LABYRINTH',`<div class="mini-board" style="grid-template-columns:repeat(6,1fr)">${Array.from({length:36},(_,i)=>{const x=i%6,y=Math.floor(i/6),k=`${x},${y}`;return `<button class="tic" data-maze="${k}">${x===p[0]&&y===p[1]?'P':x===5&&y===5?'G':walls.has(k)?'█':''}</button>`}).join('')}</div>`);document.querySelectorAll('[data-maze]').forEach(b=>b.onclick=()=>{const [x,y]=b.dataset.maze.split(',').map(Number);if(Math.abs(x-p[0])+Math.abs(y-p[1])!==1||walls.has(b.dataset.maze))return;p=[x,y];if(c&&Math.random()<.2)walls.delete([...walls][Math.floor(Math.random()*walls.size)]);if(x===5&&y===5)return gameDone('Maze','The exit was not on the first map.');draw()})};draw()}
  function searchMini(){let found=0;mini('SEARCH',`<p>Find the four requested objects.</p><div class="modal-grid">${['BOOK','KEY','PHOTO','APPLE'].map(x=>`<button class="slot" data-search>${x}</button>`).join('')}</div><p id="searchCount" class="note">0/4</p>`);document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{if(b.disabled)return;b.disabled=true;found++;$('searchCount').textContent=`${found}/4`;if(found>=4)gameDone('Search','You found everything. One object was not requested.')})}
  function rhythm(){let n=0;mini('RHYTHM','<p>Press SPACE eight times.</p><div style="font-size:32px;text-align:center;padding:40px">SPACE</div><p id="rh" class="note">0/8</p>');const f=e=>{if(e.code!=='Space')return;n++;$('rh').textContent=`${n}/8`;if(n>=8){document.removeEventListener('keydown',f);gameDone('Rhythm','The melody ends one beat before it should.')}};document.addEventListener('keydown',f);cleanup=()=>document.removeEventListener('keydown',f)}
  function cards(){let hp=20,en=18;const draw=()=>{mini('CARD DUEL',`<p>You ${hp} HP · Opponent ${en} HP</p><div class="modal-grid"><button class="mini-btn" id="a">ATTACK +4</button><button class="mini-btn" id="m">MAGIC +7</button></div>`);const play=d=>{en-=d;hp-=Math.max(0,Math.floor(Math.random()*5)-1);if(en<=0)return gameDone('Card Duel','Victory. Your opponent asks who taught you that move.');if(hp<=0)return gameDone('Card Duel','Defeat. The opponent refuses to remember how they won.');draw()};$('a').onclick=()=>play(4);$('m').onclick=()=>play(7)};draw()}
  function runner(){let n=0;mini('RUN','<p>Survive eight seconds.</p><div class="runner"></div><p id="run" class="note">0.0s</p>');const start=performance.now(),timer=setInterval(()=>{n=(performance.now()-start)/1000;$('run').textContent=`${n.toFixed(1)}s`;if(n>=8){clearInterval(timer);gameDone('Runner','You escaped. There was never anything behind you.')}},100);cleanup=()=>clearInterval(timer)}
  function switches(){let b=[0,0,0,0,0];const goal='10101';const draw=()=>{mini('LOGICAL SWITCHES',`<p>Make ${goal}</p><div class="modal-grid">${b.map((v,i)=>`<button class="slot" data-sw="${i}">${v}</button>`).join('')}</div>`);document.querySelectorAll('[data-sw]').forEach(x=>x.onclick=()=>{const i=+x.dataset.sw;b[i]^=1;if(i)b[i-1]^=1;if(i<4)b[i+1]^=1;if(b.join('')===goal)return gameDone('Switches','The pattern matches a save timestamp.');draw()})};draw()}
  function cipher(){mini('CIPHER','<p>Decode 3-15-4-5.</p><div class="quiz-options"><button class="mini-btn" id="code">CODE</button><button class="mini-btn">SAVE</button><button class="mini-btn">LOOP</button></div>');$('code').onclick=()=>gameDone('Cipher','Correct. The plaintext was CODE. Then the screen adds: “FOR YOU.”')}
  function delivery(){let n=0;mini('DELIVERY','<p>Deliver five parcels.</p><div class="modal-grid">'+['Library','Bakery','Farm','Boutique','Animal House'].map(x=>`<button class="slot" data-del>${x}</button>`).join('')+'</div>');document.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{x.disabled=true;n++;if(n>=5)gameDone('Delivery','All deliveries complete. One address was not there before.')})}
  function fishing(){let n=0;mini('FISHING','<button class="mini-btn" id="fish">CAST</button><p id="fc" class="note">0/5</p>');$('fish').onclick=()=>{n++;$('fc').textContent=`${n}/5`;if(n>=5)gameDone('Fishing',S.corruption>25?'The final catch has no name.':'A perfectly ordinary fish.')}}
  function differences(){let n=0;mini('FIND DIFFERENCES',`<p>Find five changes.</p><div class="modal-grid">${['SUN','TREE','CLOCK','FLOWER','CLOUD'].map(x=>`<button class="slot" data-diff>${x}</button>`).join('')}</div><p id="df" class="note">0/5</p>`);document.querySelectorAll('[data-diff]').forEach(x=>x.onclick=()=>{if(x.disabled)return;x.disabled=true;n++;$('df').textContent=`${n}/5`;if(n>=5)gameDone('Differences','You found five differences. There were six.')})}
  function quiz(){mini('QUIZ','<p>What changes across loops?</p><div class="quiz-options"><button class="mini-btn" id="memoryAnswer">MEMORY</button><button class="mini-btn">WEATHER</button></div>');$('memoryAnswer').onclick=()=>gameDone('Quiz','Correct. The answer was stable this time.')}
  function reaction(){let n=0,keys=['SPACE','ENTER','Q','W'];mini('REACTION','<p>Press the shown key eight times.</p><div id="key" style="font-size:32px;text-align:center;padding:40px">SPACE</div><p id="rc" class="note">0/8</p>');const f=e=>{const k=$('key').textContent;const ok=(k==='SPACE'&&e.code==='Space')||(k==='ENTER'&&e.code==='Enter')||(k==='Q'&&e.code==='KeyQ')||(k==='W'&&e.code==='KeyW');if(!ok)return;n++;$('rc').textContent=`${n}/8`;if(n>=8){document.removeEventListener('keydown',f);return gameDone('Reaction','Perfect. Something pressed the key with you.')}$('key').textContent=keys[Math.floor(Math.random()*keys.length)]};document.addEventListener('keydown',f);cleanup=()=>document.removeEventListener('keydown',f)}
  function harvest(){let n=0;mini('HARVEST','<p>Click ten apples.</p><div id="ha" style="height:280px;position:relative"></div><p id="hc" class="note">0/10</p>');for(let i=0;i<12;i++){const b=document.createElement('button');b.className='gem';b.textContent=Math.random()<.12?'●':'🍎';b.style.position='absolute';b.style.left=`${Math.random()*90}%`;b.style.top=`${Math.random()*80}%`;b.onclick=()=>{if(b.textContent==='●')return add('courage',-2);n++;b.remove();$('hc').textContent=`${n}/10`;if(n>=10)gameDone('Harvest','One bad apple was counting with you.')} ;$('ha').appendChild(b)}}
  function flight(){let n=0;mini('FLIGHT','<p>Fly through ten cloud gates.</p><button class="mini-btn" id="fly">FLY</button><p id="fl" class="note">0/10</p>');$('fly').onclick=()=>{n++;$('fl').textContent=`${n}/10`;if(n>=10)gameDone('Flight','You made the final turn before the map loaded.')}}
  function pattern(){const target=[1,3,2,4];let input=[];mini('MAGIC PATTERN',`<p>Repeat: <b>1 · 3 · 2 · 4</b></p><div class="modal-grid">${[1,2,3,4].map(x=>`<button class="slot" data-pat="${x}">${x}</button>`).join('')}</div>`);document.querySelectorAll('[data-pat]').forEach(b=>b.onclick=()=>{input.push(+b.dataset.pat);if(!input.every((x,i)=>x===target[i]))return input=[];if(input.length===4)gameDone('Pattern','The spell completes. The room becomes one frame brighter.')})}
  function gallery(){modal('GALLERY',`<div class="modal-grid"><div class="doc"><b>ENDINGS</b><div class="note">${S.endings.length}/6</div></div><div class="doc"><b>ITEMS</b><div class="note">${S.inventory.length}</div></div><div class="doc"><b>MINI-GAMES</b><div class="note">${Object.keys(S.games).length}/18</div></div></div>`)}
  function settings(){const modes=['FRIENDLY','NORMAL','NIGHTMARE','CORRUPTED','???'];modal('SETTINGS',`<div class="slot"><b>DIFFICULTY</b><p>${S.difficulty}</p><button class="mini-btn" id="mode">Cycle</button></div>`);$('mode').onclick=()=>{S.difficulty=modes[(modes.indexOf(S.difficulty)+1)%modes.length];if(S.difficulty==='CORRUPTED')S.corruption+=5;persist();settings()}}
  function saveMenu(){modal('SAVE GAME',`<div class="modal-grid">${[1,2,3].map(i=>`<button class="slot" data-save="${i}"><b>SAVE ${String(i).padStart(2,'0')}</b><br><span class="note">${S.location}</span></button>`).join('')}</div>`);document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{S.saves++;localStorage.setItem(`${SLOT}${b.dataset.save}`,JSON.stringify(S));persist();closeModal();renderScene(`${$('scene').innerHTML}\n\n<span class="system">${S.corruption>45?'MEMORY SAVED.':'GAME SAVED.'}</span>${S.corruption>60?'\n<span class="warning">WHY DID YOU SAVE HERE?</span>':''}`,[['Continue',()=>{}]],S.location,S.chapter)})}
  function loadMenu(){modal('LOAD GAME',`<div class="modal-grid">${[1,2,3].map(i=>{let x=null;try{x=JSON.parse(localStorage.getItem(`${SLOT}${i}`))}catch{}return `<button class="slot" data-load="${i}"><b>SAVE ${String(i).padStart(2,'0')}</b><br><span class="note">${x?`LAST LOCATION: ${x.location}<br>STATUS: ${x.corruption>40?'CORRUPTED':'NORMAL'}`:'EMPTY SLOT'}</span></button>`}).join('')}</div>`);document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{let x=null;try{x=JSON.parse(localStorage.getItem(`${SLOT}${b.dataset.load}`))}catch{}if(!x)return;S=x;S.loads=(S.loads||0)+1;S.memory=clamp((S.memory||0)+2);S.corruption=clamp((S.corruption||0)+Math.min(10,S.loads));persist();closeModal();showGame();renderScene(`<span class="warning">You loaded this day again.</span>\n\n<span class="system">LAST LOCATION: ${S.location||'???'}</span>`,[['Continue',resume]],S.location||'Ponyville',S.chapter||'ACT')})}
  function resume(){if(!S.player)return chooseCharacter();if(S.act>=7)return core();if(S.act>=5)return entity();if(S.act>=4)return other();if(S.act>=3)return echo();if(S.act>=2)return glitch();prologue()}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;({save:saveMenu,inventory:()=>modal('INVENTORY',S.inventory.length?`<div class="modal-grid">${S.inventory.map(i=>`<div class="item"><b>${i}</b></div>`).join('')}</div>`:'<p>Empty.</p>'),menu:showMenu}[b.dataset.action]||(()=>{}))()});
  function boot(){const bootEl=$('boot'),app=$('app'),line=$('bootLine'),bar=$('bootBar');if(!bootEl||!app||!line||!bar)return;const text=['initializing friendship memory...','loading Ponyville...','checking old saves...','restoring characters...','warning: memory mismatch','ready.'];let p=0;const timer=setInterval(()=>{p+=20;bar.style.width=`${Math.min(p,100)}%`;line.textContent=text[Math.min(Math.floor(p/20),text.length-1)];if(p>=100){clearInterval(timer);bootEl.classList.add('hidden');app.classList.remove('hidden');menu()}},120)}
  boot();
})();
