(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const KEY = 'last-save-state-v2';
  const chars = {
    twilight:['TWILIGHT','MAGIC'], fluttershy:['FLUTTERSHY','EMPATHY'], pinkie:['PINKIE PIE','CHAOS'],
    applejack:['APPLEJACK','HARVEST'], rarity:['RARITY','FOCUS'], rainbow:['RAINBOW DASH','SPEED']
  };
  const npcs = ['Twilight','Fluttershy','Pinkie Pie','Applejack','Rarity','Rainbow Dash'];
  const initial = () => ({player:null,name:'',difficulty:'NORMAL',act:0,scene:'prologue',location:'Ponyville',friendship:15,courage:15,attention:15,trust:15,memory:0,corruption:0,saves:0,loads:0,loops:0,inventory:[],flags:{book:false,bookOpen:false,door:false,echo:false,other:false,entity:false,core:false,newGamePlus:false},rels:Object.fromEntries(npcs.map(n=>[n,20])),visits:{},games:{},endings:[],settings:{music:true,shake:true,text:1},lastSaveLocation:'Ponyville'});
  let S = loadPersistent();
  let miniCleanup = null;
  function loadPersistent(){try{return JSON.parse(localStorage.getItem(KEY))||initial()}catch{return initial()}}
  function persist(){localStorage.setItem(KEY,JSON.stringify(S))}
  function clamp(n){return Math.max(0,Math.min(100,Math.round(n)))}
  function add(k,n){S[k]=clamp((S[k]||0)+n)}
  function rel(n,k){S.rels[n]=clamp((S.rels[n]||0)+k)}
  function item(x){if(!S.inventory.includes(x))S.inventory.push(x)}
  function has(x){return S.inventory.includes(x)}
  function hit(k){S.games[k]=(S.games[k]||0)+1;add('friendship',2);add('memory',1);persist()}
  function visits(l){S.visits[l]=(S.visits[l]||0)+1}
  function newRun(id){const old=S;S=initial();S.player=id;S.name=chars[id][0];S.loops=old.loops||0;S.endings=old.endings||[];S.difficulty=old.difficulty||'NORMAL';S.corruption=Math.max(0,(old.corruption||0)-10);S.memory=old.memory||0;S.flags.newGamePlus=!!old.flags?.newGamePlus;if(S.flags.newGamePlus){add('attention',20);add('memory',15)}persist();showGame();scene('prologue')}
  function menu(){ $('game').classList.add('hidden'); $('menu').classList.remove('hidden'); renderMenu() }
  function showGame(){ $('menu').classList.add('hidden'); $('game').classList.remove('hidden') }
  function renderMenu(){
    const label=S.corruption>65?'YOU ALREADY PLAYED THIS.':S.corruption>30?'RESTART':'NEW GAME';
    $('menu').innerHTML=`<div class="menu-card"><h1 class="title">MY LITTLE PONY:<br>THE LAST SAVE</h1><div class="subtitle">Friendship was never deleted.</div><div class="menu-buttons">
    <button class="menu-btn" id="new">${label}<span class="small">begin another ordinary day</span></button>
    <button class="menu-btn" id="load">LOAD GAME<span class="small">the saves remember more than you do</span></button>
    <button class="menu-btn" id="gallery">GALLERY<span class="small">${S.endings.length}/6 endings</span></button>
    <button class="menu-btn" id="settings">SETTINGS<span class="small">audio · video · accessibility</span></button>
    <button class="menu-btn" id="about">ABOUT<span class="small">a narrative horror experiment</span></button>
    <button class="menu-btn" id="exit">EXIT<span class="small">close window</span></button></div><div class="footer">v1.0.0 · local saves · 18 mini-games · ${S.difficulty}</div></div>`;
    $('new').onclick=chooseCharacter;$('load').onclick=loadPanel;$('gallery').onclick=gallery;$('settings').onclick=settings;$('about').onclick=()=>modal('ABOUT','<p><b>THE LAST SAVE</b> is a standalone narrative horror adventure about memory, repetition, and the price of keeping a perfect world unchanged.</p><p>The horror is built from inconsistencies, not constant jump scares.</p>');$('exit').onclick=()=>window.close();
  }
  function modal(title,body){$('overlay').classList.remove('hidden');$('overlay').innerHTML=`<div class="modal"><button class="close" id="x">✕</button><h2>${title}</h2>${body}</div>`;$('x').onclick=closeModal}
  function closeModal(){$('overlay').classList.add('hidden');$('overlay').innerHTML='';if(miniCleanup){miniCleanup();miniCleanup=null}}
  function chooseCharacter(){modal('CHOOSE YOUR CHARACTER',`<p>Your choice changes skills, dialogue and which mini-games get easier.</p><div class="modal-grid">${Object.entries(chars).map(([id,c])=>`<button class="slot" data-c="${id}"><b>${c[0]}</b><br><span class="note">SPECIALTY: ${c[1]}</span></button>`).join('')}</div>`);document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{closeModal();newRun(b.dataset.c)})}
  function scene(id,text,choices,location='Ponyville',title='PROLOGUE — AN ORDINARY DAY'){
    S.scene=id;S.location=location;S.chapter=title;visits(location);updateHud();$('chapterLabel').textContent=title;$('locationTitle').textContent=location;$('scene').innerHTML=text;$('choices').innerHTML=(choices||[]).map((c,i)=>`<button class="choice-btn" data-i="${i}"><strong>${i+1}.</strong> ${c[0]}</button>`).join('');document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>choices[+b.dataset.i][1]());if(S.corruption>55)document.body.classList.add('corrupted');else document.body.classList.remove('corrupted');persist()}
  function prologue(){
    scene('prologue',`<span class="quote">${S.name}</span> wakes to sunlight, birdsong and the quiet certainty that this is the first time today has happened.${S.flags.newGamePlus?'\n\n<span class="warning">You remember the shape of this morning.</span>':''}\n\nPonyville is normal. Pinkie is loud. Twilight has too many books. Applejack needs help. Fluttershy is waiting by her door.`,[
      ['Visit Twilight at the library',library],['Find Pinkie Pie',pinkie],['Help Applejack',applejack],['Visit Fluttershy',flutter],['Explore the Everfree Forest',forest],['Open the activity board',activityBoard]
    ])
  }
  function library(){add('attention',2);rel('Twilight',4);scene('library',`Twilight asks you to sort a shelf. Behind an atlas you find a book with no title, author or catalogue number. Its cover is warm.\n\n<span class="quote">Twilight:</span> “That wasn't there yesterday.”`,[
    ['Touch it',()=>{S.flags.book=true;add('courage',2);scene('library',`There is a keyhole in the spine. You do not have a key.\n\nThen a key falls from a shelf that was empty a moment ago.`,[['Take the key',()=>{item('Old Key');scene('library',`The key fits. The cover opens by itself.\n\n<span class="system">FRIENDSHIP.EXE</span>\n<span class="warning">DON'T LET HER REMEMBER.</span>`,[['Read the page',bookOpen],['Close it',weirdDay]])}],[ 'Leave it alone',weirdDay]])}],
    ['Ask Twilight to inspect it',()=>{rel('Twilight',8);weirdDay()}],['Ignore it and return later',pinkie]] )
  }
  function bookOpen(){S.flags.bookOpen=true;S.act=1;add('memory',8);S.corruption+=8;item('Fragment of Book');scene('book','Twilight reads the line twice.\n\nThe room becomes completely silent.\n\nNo birds. No clock. No wind.\n\n<span class="quote">Twilight:</span> “Who is ‘her’?”\n\nA page turns without being touched.',[['Continue',glitch],['Close the book',glitch]],'Golden Oak Library','ACT I — THE LOST BOOK')}
  function weirdDay(){S.corruption+=2;scene('town',`The rest of the day feels normal. Almost.\n\nPinkie tells a joke you have never heard. Then she laughs and says, “No, wait. You already heard this.”`,[['Ask about it',()=>{add('memory',4);rel('Pinkie Pie',8);glitch()}],['Pretend it was nothing',glitch],['Play a quick mini-game',()=>miniTicTacToe()]],'Ponyville','ACT I — THE LOST BOOK')}
  function pinkie(){rel('Pinkie Pie',4);add('friendship',3);scene('pinkie',`Pinkie has prepared a surprise game. She smiles too widely for a second.\n\n<span class="quote">Pinkie:</span> “I knew you'd choose this option.”`,[['Play tic-tac-toe',miniTicTacToe],['Ask how she knew',()=>{add('attention',6);S.corruption+=4;glitch()}],['Help decorate',()=>{rel('Pinkie Pie',6);add('friendship',5);applejack()}]])}
  function applejack(){rel('Applejack',4);scene('orchard',`Applejack needs help collecting apples. One fruit is completely black.\n\nShe walks past it without looking.\n\nYou can smell it from across the orchard.`,[['Pick it',()=>{item('Black Apple');add('attention',7);S.corruption+=3;weirdDay()}],['Leave it',weirdDay],['Ask Applejack',()=>{rel('Applejack',6);add('trust',4);weirdDay()}],['Play harvest',miniHarvest]],'Sweet Apple Acres','ACT I — THE LOST BOOK')}
  function flutter(){rel('Fluttershy',6);add('trust',4);scene('flutter',`Fluttershy asks you to stay.\n\n<span class="quote">Fluttershy:</span> “Something has been walking around the house. It only comes when the save icon appears.”`,[['Stay',()=>{rel('Fluttershy',12);add('friendship',5);weirdDay()}],['Leave',()=>{add('courage',3);weirdDay()}],['Ask why',()=>{add('attention',6);add('memory',3);weirdDay()}]])}
  function forest(){S.location='Everfree Forest';add('courage',6);scene('forest',`The forest is unnaturally still. A shard of an Element is embedded in a tree root.\n\nIt hums when you hold it.`,[['Take the shard',()=>{item('Element Shard');add('memory',7);glitch()}],['Leave it',weirdDay],['Play the labyrinth',()=>miniMaze(false)]],'Everfree Forest','ACT II — THE GLITCH')}
  function glitch(){S.act=2;S.corruption+=7;add('memory',5);scene('glitch',`<span class="system">23:07</span>\n\nThe library is identical.\nExcept the books are in a different order.\nExcept the clock is moving backward.\nExcept there is a door where a bookshelf should be.\n\nYou hear hoofsteps behind you.\nNobody enters.`,[['Open the new door',alternateLibrary],['Touch the clock',()=>{item('Stopped Clock Hand');add('attention',8);alternateLibrary()}],['Call Twilight',()=>{rel('Twilight',5);alternateLibrary()}],['Play Memory',miniMemory]],'Golden Oak Library · 23:07','ACT II — THE GLITCH')}
  function alternateLibrary(){S.flags.door=true;S.corruption+=7;item('Photo');scene('glitch2',`The door leads to another copy of the library.\nA photograph shows six ponies.\n\nBlink.\n\nSeven.\n\nYou are certain the seventh was not there before.`,[['Look again',()=>{add('attention',8);scene('glitch3',`The seventh pony has no face.\n\nIt is standing behind you in the photograph.\n\n<span class="system">PHOTO UPDATED.</span>`,[['Turn around',echo],['Do not turn around',echo]],'Golden Oak Library // Memory Copy','ACT II — THE GLITCH')}],['Take the photo',echo],['Play three in a row',miniThree]],'Golden Oak Library // Memory Copy','ACT II — THE GLITCH')}
  function echo(){S.act=3;S.flags.echo=true;S.corruption+=10;add('memory',10);scene('echo',`The town archive contains no books. It contains save records.\n\n<span class="system">SAVE_0001</span>\n<span class="system">SAVE_0014</span>\n<span class="system">SAVE_0039</span>\n<span class="system">SAVE_0107</span>\n\nEvery record ends with a disappearance.\nEvery record is followed by a reset.`,[['Read SAVE_0039',()=>archive],['Search for your name',searchPlayer],['Play the cipher',miniCipher],['Go to the other Ponyville',otherPonyville]],'Old Ponyville Archive','ACT III — ECHO')}
  function archive(){add('attention',6);item('Archive Record');scene('archive',`<span class="system">SAVE_0039</span>\nPLAYER: ${S.name}\nCHOICE: “I tried to save them.”\nEND: FORGOTTEN\n\nThe record contains the exact sentence you were about to say.`,[['Follow it',otherPonyville],['Burn the record',()=>{add('courage',4);otherPonyville()}]],'Old Ponyville Archive','ACT III — ECHO')}
  function searchPlayer(){S.corruption+=8;add('memory',8);scene('search',`<span class="system">SEARCH RESULTS: ${S.name}</span>\n\n107 previous records.\n\n<span class="warning">YOU HAVE BEEN HERE BEFORE.</span>\n\nOne clean file remains:\n“Every time I save them, I lose myself.”`,[['Open it',entity],['Close it',otherPonyville]],'Old Ponyville Archive','ACT III — ECHO')}
  function otherPonyville(){S.act=4;S.flags.other=true;S.corruption+=12;scene('other',`<span class="warning">PONYVILLE // MEMORY COPY</span>\n\nThe sky is nearly black. The houses are perfect. Nobody moves.\n\nFluttershy is waiting in the square.\n\n<span class="quote">Fluttershy:</span> “In the last one, you left me here.”`,[['Ask what she means',entity],['Apologize',()=>{rel('Fluttershy',12);add('friendship',6);entity()}],['Leave the square',()=>{add('courage',6);entity()}],['Play corrupted maze',()=>miniMaze(true)]],'Ponyville // Memory Copy','ACT IV — THE OTHER PONYVILLE')}
  function entity(){S.act=5;S.flags.entity=true;S.corruption+=13;add('memory',12);scene('entity',`A voice comes from outside the screen.\n\n<span class="quote">SHE:</span> “I am the part of Ponyville that remembers.”\n\n“I reset the day when friendship breaks.”\n“I erase memories when truth threatens the loop.”\n“And every time you reload, I remember you.”`,[['Ask who she is',()=>{add('memory',10);fracture()}],['Refuse to believe her',()=>{S.corruption+=8;fracture()}],['Ask what happens if the loop stops',()=>{add('attention',10);fracture()}],['Play reaction test',miniReaction]],'The Place Between Saves','ACT V — SHE')}
  function fracture(){S.act=7;S.flags.core=true;S.corruption+=15;scene('core',`<span class="system">WORLD CORE</span>\n\nWORLD\nCHARACTERS\nMEMORY\nPLAYER\n\nA terminal waits. The last page of FRIENDSHIP.EXE is missing.\n\nThe system asks whether you are sure you want to edit a world that cannot save itself.`,[['Explore PLAYER data',playerData],['Insert the last page',()=>{item('Last Page');finalChoice()}],['Play magic pattern',miniPattern]],'World Core','ACT VII — THE FRACTURE')}
  function playerData(){scene('player',`<span class="system">PLAYER</span>\n\nCHARACTER: ${S.name}\nSAVES: ${S.saves}\nLOADS: ${S.loads}\nLOOPS: ${S.loops}\nMEMORY: ${S.memory}%\nITEMS: ${S.inventory.length}\nMINI-GAMES: ${Object.keys(S.games).length}/18\n\n<span class="warning">THIS DATA IS NOT SUPPOSED TO BE VISIBLE.</span>`,[['Continue',finalChoice]],'World Core','ACT VII — THE FRACTURE')}
  function finalChoice(){const perfect=S.inventory.length>=7&&Object.keys(S.games).length>=18&&S.memory>=55&&S.loads>=1;scene('final',`<span class="system">FINAL SEQUENCE</span>\n\nThree commands are available.\n\n<span class="quote">SHE:</span> “Please. Keep them together.”\n\n${perfect?'<span class="system">SECRET CONDITION MET: MEMORY COMPLETE.</span>':''}`,[['SAVE THE WORLD',()=>end('LOOP')],['BREAK THE WORLD',()=>end('CORRUPTION')],[perfect?'FREE THEM — TRUE':'FREE THEM',()=>end(perfect?'SECRET':'FORGOTTEN')]],'World Core','FINAL CHOICE')}
  function end(type){const text={LOOP:`<span class="system">ENDING 02 — LOOP</span>\n\nThe world resets. Everyone smiles.\n\nPinkie looks directly at the screen.\n\n<span class="quote">“You're early this time.”</span>`,CORRUPTION:`<span class="warning">ENDING 04 — CORRUPTION</span>\n\nPonyville is deleted one object at a time.\nThe last thing remaining is the cursor.`,FORGOTTEN:`<span class="system">ENDING 03 — FORGOTTEN</span>\n\nYour name is removed from every save.\nThe town continues without you.`,SECRET:`<span class="system">ENDING 06 — ???</span>\n\nYou break the system without destroying the world.\n\nEveryone remembers.\nEven her.\n\nThe screen goes white, not black.`,TRUTH:`<span class="system">ENDING 05 — TRUTH</span>\n\nThe memory engine is released.\nThe world is allowed to change for the first time.`};
    const key=type==='SECRET'?'???':type;if(!S.endings.includes(key))S.endings.push(key);S.loops++;S.flags.newGamePlus=true;S.corruption=clamp(S.corruption+8);persist();scene('ending',text[ type ],[['Return to title',menu],['START NEW GAME+',()=>newRun(S.player)]],'Ponyville','ENDING')}

  // ---------- 18 mini-games ----------
  function miniShell(title,html,close=true){if(miniCleanup){miniCleanup();miniCleanup=null}$('overlay').classList.remove('hidden');$('overlay').innerHTML=`<div class="modal"><button class="close" id="mx">✕</button><h2>${title}</h2>${html}</div>`;$('mx').onclick=closeModal;if(!close) $('mx').classList.add('hidden')}
  function done(name,bonus=3,msg='Completed.'){hit(name);add('attention',bonus>3?1:0);$('miniBody')?.remove();$('overlay').querySelector('.modal').insertAdjacentHTML('beforeend',`<p>${msg}</p><button class="mini-btn" id="continueMini">Continue</button>`);$('continueMini').onclick=closeModal}
  function activityBoard(){modal('ACTIVITY BOARD',`<p>All 18 games exist as real playable systems. Progress is remembered.</p><div class="modal-grid">${['ticTacToe','threeMatch','memory','maze','search','rhythm','cards','runner','switches','cipher','delivery','fishing','differences','quiz','reaction','harvest','flight','pattern'].map((x,i)=>`<button class="slot" data-game="${x}"><b>${i+1}. ${x.toUpperCase()}</b><span class="note">clears: ${S.games[x]||0}</span></button>`).join('')}</div>`);document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>miniByName(b.dataset.game))}
  function miniByName(n){closeModal();({ticTacToe:miniTicTacToe,threeMatch:miniThree,memory:miniMemory,maze:()=>miniMaze(false),search:miniSearch,rhythm:miniRhythm,cards:miniCards,runner:miniRunner,switches:miniSwitches,cipher:miniCipher,delivery:miniDelivery,fishing:miniFishing,differences:miniDifferences,quiz:miniQuiz,reaction:miniReaction,harvest:miniHarvest,flight:miniFlight,pattern:miniPattern}[n]||miniQuiz)()}
  function miniTicTacToe(){let b=Array(9).fill(''),turn='X';const win=()=>[[0,1,2],[3,4,5],[6,7,8],[0,4,8],[2,4,6],[0,3,6],[1,4,7],[2,5,8]].some(([a,c,d])=>b[a]&&b[a]===b[c]&&b[a]===b[d]);const draw=()=>{miniShell('TIC-TAC-TOE',`<p>Beat Pinkie. She may cheat after 30% corruption.</p><div class="mini-board" style="grid-template-columns:repeat(3,1fr)">${b.map((v,i)=>`<button class="tic" data-t="${i}">${v}</button>`).join('')}</div>`);document.querySelectorAll('[data-t]').forEach(x=>x.onclick=()=>move(+x.dataset.t))};const finish=m=>{done('ticTacToe',4,m)};function move(i){if(b[i])return;b[i]='X';if(win())return finish('YOU WIN. Pinkie says she remembers losing.');let e=b.map((v,j)=>v?null:j).filter(v=>v!==null);if(!e.length)return finish('DRAW. Pinkie claims victory.');b[e[Math.floor(Math.random()*e.length)]]='O';if(win())return finish('Pinkie wins. She knew where you would move.');draw()}draw()}
  function miniThree(){let g=Array.from({length:36},()=>['♥','★','🍎','🪽'][Math.floor(Math.random()*4)]),sets=0;const draw=()=>{miniShell('THREE IN A ROW',`<p>Click three matching symbols. Goal: 5 sets.</p><div class="match-grid">${g.map((x,i)=>`<button class="gem" data-g="${i}">${x}</button>`).join('')}</div><p class="note">sets ${sets}/5</p>`);let pick=[];document.querySelectorAll('[data-g]').forEach(x=>x.onclick=()=>{pick.push(+x.dataset.g);if(pick.length===3){if(pick.every(i=>g[i]===g[pick[0]])){sets++;pick.forEach(i=>g[i]=['♥','★','🍎','🪽'][Math.floor(Math.random()*4)])}pick=[];if(sets>=5)done('threeMatch',4,'Five sets. The board quietly contains one symbol you never saw before.');else draw()}})};draw()}
  function miniMemory(){let a=['♥','♥','★','★','🍎','🍎','🪽','🪽'].sort(()=>Math.random()-.5),o=[],m=[];const draw=()=>{miniShell('MEMORY',`<p>Find all four pairs.</p><div class="memory-grid">${a.map((x,i)=>`<button class="mem" data-m="${i}">${m.includes(i)||o.includes(i)?x:'?'}</button>`).join('')}</div><p class="note">pairs ${m.length/2}/4</p>`);document.querySelectorAll('[data-m]').forEach(x=>x.onclick=()=>{const i=+x.dataset.m;if(o.includes(i)||m.includes(i))return;o.push(i);draw();if(o.length===2){if(a[o[0]]===a[o[1]])m.push(...o);setTimeout(()=>{o=[];draw();if(m.length===8)done('memory',4,'All pairs found. One card changed while you were looking away.')},250)}})};draw()}
  function miniMaze(c){let p=[0,0],goal=[5,5],walls=new Set(['1,0','1,1','1,2','3,2','4,2','4,3','2,4','3,4']);const draw=()=>{miniShell(c?'CORRUPTED MAZE':'LABYRINTH',`<p>${c?'The map changes after some moves.':'Reach G.'}</p><div class="mini-board" style="grid-template-columns:repeat(6,1fr)">${Array.from({length:36},(_,i)=>{let x=i%6,y=Math.floor(i/6),k=`${x},${y}`;return `<button class="tic" data-maze="${k}">${x===p[0]&&y===p[1]?'P':x===5&&y===5?'G':walls.has(k)?'█':''}</button>`}).join('')}</div>`);document.querySelectorAll('[data-maze]').forEach(x=>x.onclick=()=>move(x.dataset.maze))};const move=k=>{let [x,y]=k.split(',').map(Number);if(Math.abs(x-p[0])+Math.abs(y-p[1])!==1||walls.has(k))return;p=[x,y];if(c&&Math.random()<.2){const a=[...walls][Math.floor(Math.random()*walls.size)];walls.delete(a)}if(x===5&&y===5)return done('maze',4,'The exit was not on the first map.');draw()};draw()}
  function miniSearch(){let targets=['book','key','apple','photo'];let found=0;miniShell('SEARCH OBJECTS',`<p>Find four targets among the boxes. They relocate when clicked.</p><div class="modal-grid">${Array.from({length:16},(_,i)=>`<button class="slot" data-s="${i}">${targets[i%4]}</button>`).join('')}</div><p class="note" id="sm">0 / 4</p>`);document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{if(b.dataset.done)return;if(b.textContent==='book'||b.textContent==='key'||b.textContent==='photo'){b.dataset.done=1;found++;b.disabled=true;$('sm').textContent=`${found} / 4`;if(found===4)done('search',4,'You found everything. One target was not requested.') }})}
  function miniRhythm(){let n=0;miniShell('RHYTHM',`<p>Press SPACE eight times in rhythm.</p><div style="font:30px 'Press Start 2P';text-align:center;padding:60px">SPACE</div><p class="note">hits <span id="rh">0</span>/8</p>`);const on=e=>{if(e.code==='Space'){n++;$('rh').textContent=n;if(n===8){document.removeEventListener('keydown',on);done('rhythm',4,'The melody ends one beat before the song should.') }}};document.addEventListener('keydown',on);miniCleanup=()=>document.removeEventListener('keydown',on)}
  function miniCards(){let hp=20,eh=18;const draw=()=>{miniShell('CARD DUEL',`<p>You: ${hp} HP · Opponent: ${eh} HP</p><div class="modal-grid"><button class="mini-btn" id="atk">ATTACK +4</button><button class="mini-btn" id="def">DEFEND</button><button class="mini-btn" id="mag">MAGIC +7</button></div>`);$('atk').onclick=()=>play(4);$('def').onclick=()=>play(1);$('mag').onclick=()=>play(7)};const play=d=>{eh-=d;hp-=Math.max(0,Math.floor(Math.random()*6)-1);if(eh<=0)return done('cards',4,'Victory. Your opponent asks who taught you that move.');if(hp<=0)return done('cards',1,'Defeat. The opponent refuses to remember how they won.');draw()};draw()}
  function miniRunner(){let t=0,raf,start=performance.now();miniShell('RUN',`<p>Press SPACE to jump. Survive 12 seconds.</p><div class="runner" id="rr"><div class="pony"></div><div class="ground"></div></div><p class="runner-hint" id="rt">0.0s</p>`);let y=0,vy=0,last=performance.now();const key=e=>{if(e.code==='Space'&&y===0)vy=-10};document.addEventListener('keydown',key);function frame(now){let dt=Math.min(.03,(now-last)/1000);last=now;y=Math.max(0,y+vy*dt);vy+=25*dt;$('rr').querySelector('.pony').style.bottom=`${45+y*3}px`;t=(now-start)/1000;$('rt').textContent=t.toFixed(1)+'s';if(t>=12){document.removeEventListener('keydown',key);return done('runner',5,'You escaped. There was never anything behind you.')}raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame);miniCleanup=()=>{cancelAnimationFrame(raf);document.removeEventListener('keydown',key)}}
  function miniSwitches(){let bits=[0,0,0,0,0],moves=0;const goal='10101';const draw=()=>{miniShell('LOGICAL SWITCHES',`<p>Make the pattern <b>${goal}</b>. Some hints are deliberately false after corruption 40.</p><div class="modal-grid">${bits.map((x,i)=>`<button class="slot" data-sw="${i}">SWITCH ${i+1}: ${x}</button>`).join('')}</div><p class="note">moves ${moves}</p>`);document.querySelectorAll('[data-sw]').forEach(b=>b.onclick=()=>{let i=+b.dataset.sw;bits[i]^=1;if(i>0)bits[i-1]^=1;if(i<4)bits[i+1]^=1;moves++;if(bits.join('')===goal)done('switches',4,'The correct pattern matches a save timestamp.');else draw()})};draw()}
  function miniCipher(){let a=['CODE','SAVE','LOOP'],ans=a[S.memory%3];miniShell('CIPHER',`<p>Decode <b>3-15-4-5</b> using A1Z26.</p><div class="quiz-options">${a.map(x=>`<button class="mini-btn" data-ci="${x}">${x}</button>`).join('')}</div>`);document.querySelectorAll('[data-ci]').forEach(b=>b.onclick=()=>{if(b.dataset.ci==='CODE')done('cipher',4,'Correct. The plaintext was CODE. Then the screen adds: “FOR YOU.”');else{add('attention',-2);closeModal()}})}
  function miniDelivery(){let left=5;miniShell('DELIVERY',`<p>Deliver five parcels before the route changes.</p><div class="modal-grid">${['Library','Bakery','Farm','Boutique','Animal House'].map(x=>`<button class="slot" data-d>${x}</button>`).join('')}</div>`);document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{b.disabled=true;left--;if(left===0)done('delivery',4,'All deliveries complete. You do not remember one of the addresses.')})}
  function miniFishing(){let count=0;miniShell('FISHING',`<p>Click the water when the bobber is down. Five catches.</p><button class="mini-btn" id="fish">CAST</button><p id="fm" class="note">0 / 5</p>`);$('fish').onclick=()=>{count++;$('fm').textContent=`${count}/5`;if(Math.random()<.2&&S.corruption>25)$('fm').textContent='UNKNOWN CATCH';if(count>=5)done('fishing',3,'The final catch has no name.')}}
  function miniDifferences(){let found=0;miniShell('FIND DIFFERENCES',`<p>Find five changes. They appear after a delay.</p><div class="modal-grid"><div class="slot">SUN · TREE · CLOCK · FLOWER</div><div class="slot">SUN · TREE · CLOCK · FLOWER</div></div><div class="modal-grid">${['SUN','TREE','CLOCK','FLOWER','CLOUD'].map(x=>`<button class="slot" data-df>${x}</button>`).join('')}</div><p class="note">${S.corruption>35?'The differences move.':''}</p>`);document.querySelectorAll('[data-df]').forEach(b=>b.onclick=()=>{if(!b.dataset.x){b.dataset.x=1;found++;b.textContent+=' ✓'}if(found>=5)done('differences',4,'You found five differences. There were six.')})}
  function miniQuiz(){const qs=[['What is the first strange file called?','FRIENDSHIP.EXE'],['What changes across loops?','MEMORY'],['Who notices saves?','PINKIE PIE']];let q=qs[S.games.quiz%qs.length];miniShell('QUIZ',`<p>${q[0]}</p><div class="quiz-options">${qs.map(x=>`<button class="mini-btn" data-qz="${x[1]}">${x[1]}</button>`).join('')}</div>`);document.querySelectorAll('[data-qz]').forEach(b=>b.onclick=()=>{if(b.dataset.qz===q[1])done('quiz',3,'Correct. The answer was stable this time.');else{add('memory',-2);done('quiz',1,'Wrong. The question has changed.')}})}
  function miniReaction(){let n=0,cur='SPACE',keys=['SPACE','ENTER','Q','W'];miniShell('REACTION',`<p>Press the shown key eight times.</p><div id="rk" style="font:34px 'Press Start 2P';text-align:center;padding:60px">SPACE</div><p class="note" id="rm">0 / 8</p>`);const on=e=>{const shown=$('rk').textContent;if((shown==='SPACE'&&e.code==='Space')||(shown==='ENTER'&&e.code==='Enter')||(shown==='Q'&&e.code==='KeyQ')||(shown==='W'&&e.code==='KeyW')){n++;if(n>=8){document.removeEventListener('keydown',on);return done('reaction',4,'Perfect. Something pressed the key with you.')}cur=keys[Math.floor(Math.random()*keys.length)];$('rk').textContent=cur;$('rm').textContent=`${n}/8`}};document.addEventListener('keydown',on);miniCleanup=()=>document.removeEventListener('keydown',on)}
  function miniHarvest(){let n=0;miniShell('HARVEST',`<p>Click ten apples. Avoid black fruit.</p><div id="ha" class="runner" style="height:300px"></div><p class="note" id="hm">0 / 10</p>`);function fill(){const a=$('ha');a.innerHTML='';for(let i=0;i<8;i++){const b=document.createElement('button');b.className='gem';b.textContent=Math.random()<.12?'●':'🍎';b.style.position='absolute';b.style.left=`${5+Math.random()*85}%`;b.style.top=`${5+Math.random()*75}%`;b.onclick=()=>{if(b.textContent==='●')add('courage',-2);else{n++;b.remove();$('hm').textContent=`${n}/10`;if(n>=10)done('harvest',4,'Ten good apples. One bad one was counting with you.')}};a.appendChild(b)}}fill()}
  function miniFlight(){let n=0;miniShell('FLIGHT',`<p>Click through ten cloud gates.</p><div class="runner" id="fl"><div class="pony"></div></div><p id="fm2" class="note">0 / 10</p>`);$('fl').onclick=()=>{n++;$('fm2').textContent=`${n}/10`;if(n>=10)done('flight',5,'You made the final turn before the map loaded.')}}
  function miniPattern(){const target=[1,3,2,4],a=[];for(let i=0;i<4;i++)a.push(Math.ceil(Math.random()*4));miniShell('MAGIC PATTERN',`<p>Repeat the pattern: <b>1 · 3 · 2 · 4</b></p><div class="modal-grid">${[1,2,3,4].map(x=>`<button class="slot" data-pa="${x}">${x}</button>`).join('')}</div>`);document.querySelectorAll('[data-pa]').forEach(b=>b.onclick=()=>{a.push(+b.dataset.pa);let good=a.every((x,i)=>x===target[i]);if(!good){a.length=0;return}if(a.length===4)done('pattern',5,'The spell completes. The room becomes one frame brighter.')}})}

  function updateHud(){const p=chars[S.player]?.[0]||'UNKNOWN';$('playerName').textContent=p;$('clockLabel').textContent=S.corruption>40?'23:07':'09:14';$('stats').innerHTML=[['FRIENDSHIP',S.friendship],['COURAGE',S.courage],['ATTENTION',S.attention],['TRUST',S.trust],['MEMORY',clamp(S.memory)].map(x=>`<div class="stat"><b><span>${x[0]}</span><span>${x[1]}</span></b><div class="bar"><i style="width:${clamp(x[1])}%"></i></div></div>`).join('');$('relationships').innerHTML=npcs.map(n=>`<div class="rel"><b><span>${n}</span><span>${S.rels[n]}%</span></b><div class="bar"><i style="width:${S.rels[n]}%"></i></div></div>`).join('')}
  function inventory(){modal('INVENTORY',S.inventory.length?`<div class="modal-grid">${S.inventory.map((x,i)=>`<div class="item"><b>${x}</b><div class="note">${desc(x,i)}</div></div>`).join('')}</div>`:'<p>Empty.</p>')}
  function desc(x,i){return ({'Old Key':'A key to a lock that did not exist yesterday.','Fragment of Book':'A fragment from FRIENDSHIP.EXE.','Element Shard':'Cold magic from the forest.','Photo':'Six ponies. Then seven.','Black Apple':'It was warm when picked.','Stopped Clock Hand':'23:07. The only time that never changes.','Last Page':'The final page knows what you did.'})[x]||`Unknown item #${i+1}`}
  function save(slot){S.saves++;S.lastSaveLocation=S.location;add('memory',1);if(S.saves>3)S.corruption+=1;localStorage.setItem(`${KEY}-slot-${slot}`,JSON.stringify(S));persist();scene(S.scene,`${$('scene').innerHTML}\n\n<span class="system">${S.corruption>45?'MEMORY SAVED.':'GAME SAVED.'}</span>${S.corruption>60?'\n<span class="warning">WHY DID YOU SAVE HERE?</span>':''}`,[['Continue',()=>{}]],S.location,S.chapter)}
  function savePanel(){modal('SAVE GAME',`<div class="modal-grid">${[1,2,3].map(i=>`<button class="slot" data-sv="${i}"><b>SAVE ${String(i).padStart(2,'0')}</b><br><span class="note">${S.location}</span></button>`).join('')}</div><p class="note">Saves are story objects. Use them carefully.</p>`);document.querySelectorAll('[data-sv]').forEach(b=>b.onclick=()=>{save(+b.dataset.sv);closeModal()})}
  function loadPanel(){modal('LOAD GAME',`<div class="modal-grid">${[1,2,3].map(i=>{let x;try{x=JSON.parse(localStorage.getItem(`${KEY}-slot-${i}`))}catch{}return `<button class="slot" data-ld="${i}"><b>SAVE ${String(i).padStart(2,'0')}</b><br><span class="note">${x?`LAST LOCATION: ${x.lastSaveLocation||'???'}<br>STATUS: ${x.corruption>40?'CORRUPTED':'NORMAL'}`:'EMPTY SLOT'}</span></button>`}).join('')}</div>`);document.querySelectorAll('[data-ld]').forEach(b=>b.onclick=()=>{let x;try{x=JSON.parse(localStorage.getItem(`${KEY}-slot-${+b.dataset.ld}`))}catch{}if(!x)return;S=x;S.loads=(S.loads||0)+1;S.memory=(S.memory||0)+2;S.corruption=clamp((S.corruption||0)+Math.min(10,S.loads));persist();closeModal();showGame();scene('loaded',`<span class="warning">You loaded this day again.</span>\n\n<span class="system">LAST LOCATION: ${S.lastSaveLocation||'???'}</span>\n\n<span class="quote">“I asked you not to do that.”</span>`,[['Continue',()=>resume()]],S.lastSaveLocation||'Ponyville',S.chapter||'ACT')})}
  function resume(){if(S.act>=7)fracture();else if(S.act>=5)entity();else if(S.act>=4)otherPonyville();else if(S.act>=3)echo();else if(S.act>=2)glitch();else prologue()}
  function settings(){modal('SETTINGS',`<div class="modal-grid"><div class="slot"><b>AUDIO</b><p>Music: ${S.settings.music?'ON':'OFF'}</p><button class="mini-btn" id="mu">Toggle</button></div><div class="slot"><b>ACCESSIBILITY</b><p>Text speed: ${S.settings.text}x</p><button class="mini-btn" id="tx">Cycle text speed</button></div><div class="slot"><b>DIFFICULTY</b><p>${S.difficulty}</p><button class="mini-btn" id="di">Cycle</button></div></div>`);$('mu').onclick=()=>{S.settings.music=!S.settings.music;settings();persist()};$('tx').onclick=()=>{S.settings.text=S.settings.text===1?2:S.settings.text===2?3:1;settings();persist()};$('di').onclick=()=>{const x=['FRIENDLY','NORMAL','NIGHTMARE','CORRUPTED','???'];S.difficulty=x[(x.indexOf(S.difficulty)+1)%x.length];S.corruption+=S.difficulty==='CORRUPTED'?5:0;settings();persist()}}
  function gallery(){modal('GALLERY',`<div class="modal-grid"><div class="doc"><b>ENDING ARCHIVE</b><div class="note">${S.endings.length}/6 discovered</div></div><div class="doc"><b>ITEMS</b><div class="note">${S.inventory.length} found</div></div><div class="doc"><b>MINI-GAMES</b><div class="note">${Object.keys(S.games).length}/18 played</div></div><div class="doc"><b>NEW GAME+</b><div class="note">${S.flags.newGamePlus?'UNLOCKED':'LOCKED'}</div></div></div>`)}

  document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;({save:savePanel,inventory,menu}[b.dataset.action]||(()=>{}))()});
  $('bootLine').textContent='initializing friendship memory...';let p=0;const boot=setInterval(()=>{p+=12;$('bootBar').style.width=p+'%';$('bootLine').textContent=['initializing friendship memory...','loading Ponyville...','checking old saves...','restoring characters...','warning: memory mismatch','ready.'][Math.min(5,Math.floor(p/20))];if(p>=100){clearInterval(boot);setTimeout(()=>{$('boot').classList.add('hidden');$('app').classList.remove('hidden');renderMenu()},250)}},100);
})();
